/* Fadzkuruuni - SPA tunggal: router, tema, Al-Qur'an, jadwal salat, kiblat, zakat, kalender */
const $=(s,e=document)=>e.querySelector(s),$$=(s,e=document)=>[...e.querySelectorAll(s)];
const S=Object.assign({theme:'auto',fs:32,tr:true,gold:'',loc:{lat:-6.9175,lng:107.6191,n:'Bandung',tz:7},hist:[],tas:0},JSON.parse(localStorage.fz||'{}'));
const save=()=>{localStorage.fz=JSON.stringify(S);window.cloudPush&&window.cloudPush()};
const rp=n=>'Rp '+Math.round(n).toLocaleString('id-ID');
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('on');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('on'),2200)};
const theme=()=>{const d=S.theme=='dark'||(S.theme=='auto'&&matchMedia('(prefers-color-scheme:dark)').matches);document.documentElement.dataset.theme=d?'dark':'light'};
theme();matchMedia('(prefers-color-scheme:dark)').addEventListener('change',theme);

/* ---------- Ikon SVG (garis, 24px) ---------- */
const ICO={home:'<path d="M3 10.5 12 3l9 7.5V20a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"/>',book:'<path d="M2 4h7a3 3 0 0 1 3 3v14a2 2 0 0 0-2-2H2zM22 4h-7a3 3 0 0 0-3 3v14a2 2 0 0 1 2-2h8z"/>',news:'<path d="M4 4h13v15a1 1 0 0 0 1 1H5a2 2 0 0 1-2-2V5a1 1 0 0 1 1-1zM18 8h3v11a1 1 0 0 1-1 1M7 8h7M7 12h7M7 16h4"/>',cal:'<path d="M4 5h16v16H4zM4 10h16M8 3v4M16 3v4"/>',sliders:'<path d="M4 6h9M17 6h3M4 12h3M11 12h9M4 18h11M19 18h1"/><circle cx="15" cy="6" r="2"/><circle cx="9" cy="12" r="2"/><circle cx="17" cy="18" r="2"/>',beads:'<circle cx="12" cy="4.5" r="1.8"/><circle cx="17.5" cy="7" r="1.8"/><circle cx="19" cy="13" r="1.8"/><circle cx="15.5" cy="18.5" r="1.8"/><circle cx="8.5" cy="18.5" r="1.8"/><circle cx="5" cy="13" r="1.8"/><circle cx="6.5" cy="7" r="1.8"/><path d="M12 20.5V23"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',compass:'<circle cx="12" cy="12" r="9"/><path d="m15.5 8.5-2 5-5 2 2-5z"/>',users:'<circle cx="8" cy="8" r="3"/><path d="M2 20a6 6 0 0 1 12 0zM16 5.2a3 3 0 0 1 0 5.6M17 14a5 5 0 0 1 5 6"/>',moon:'<path d="M20 14a8 8 0 1 1-10-10 6.5 6.5 0 0 0 10 10z"/>',heart:'<path d="M12 20s-8-5-8-11a4.5 4.5 0 0 1 8-2.5A4.5 4.5 0 0 1 20 9c0 6-8 11-8 11z"/>',grid:'<path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m21 21-5-5"/>',pin:'<path d="M12 21s-7-6-7-11a7 7 0 0 1 14 0c0 5-7 11-7 11z"/><circle cx="12" cy="10" r="2.5"/>',back:'<path d="m15 5-7 7 7 7"/>',next:'<path d="m9 5 7 7-7 7"/>',scale:'<path d="M12 3v18M5 21h14M5 7h14M5 7l-3 7a3 3 0 0 0 6 0zM19 7l-3 7a3 3 0 0 0 6 0z"/>',lib:'<path d="M4 19V5a2 2 0 0 1 2-2h13v16H6a2 2 0 0 0 0 2h13"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v5M12 8h.01"/>',count:'<circle cx="12" cy="12" r="9"/><path d="M12 8v8M8 12h8"/>',star:'<path d="m12 3 2.7 5.6 6.1.9-4.4 4.3 1 6.1L12 17l-5.4 2.9 1-6.1L3.2 9.5l6.1-.9z"/>',mosque:'<path d="M3 21V11l2-2 2 2v10M17 21V11l2-2 2 2v10"/><path d="M7 21v-5a5 5 0 0 1 10 0v5M12 3v3M2 21h20"/>',kaaba:'<path d="m4 8 8-4 8 4v8l-8 4-8-4zM4 8l8 4 8-4M12 12v8"/>',full:'<path d="M4 9V4h5M20 9V4h-5M4 15v5h5M20 15v5h-5"/>',play:'<path d="M7 4l13 8-13 8z"/>',pause:'<path d="M8 5v14M16 5v14"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',check:'<path d="m5 12 5 5 9-10"/>',camera:'<path d="M4 8h3l2-3h6l2 3h3v12H4z"/><circle cx="12" cy="13" r="3.5"/>',flag:'<path d="M5 21V4M5 4h12l-2 4 2 4H5"/>',bell:'<path d="M6 16V11a6 6 0 0 1 12 0v5l2 2H4zM10 21h4"/>'};
const ic=(n,z=22)=>`<svg class="ic" width="${z}" height="${z}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICO[n]||''}</svg>`;
$$('[data-i]').forEach(e=>e.outerHTML=ic(e.dataset.i));

/* ---------- Data ---------- */
const NAMA="Al-Fatihah|Al-Baqarah|Ali 'Imran|An-Nisa'|Al-Ma'idah|Al-An'am|Al-A'raf|Al-Anfal|At-Taubah|Yunus|Hud|Yusuf|Ar-Ra'd|Ibrahim|Al-Hijr|An-Nahl|Al-Isra'|Al-Kahf|Maryam|Ta Ha|Al-Anbiya'|Al-Hajj|Al-Mu'minun|An-Nur|Al-Furqan|Asy-Syu'ara'|An-Naml|Al-Qasas|Al-'Ankabut|Ar-Rum|Luqman|As-Sajdah|Al-Ahzab|Saba'|Fatir|Ya Sin|As-Saffat|Sad|Az-Zumar|Gafir|Fussilat|Asy-Syura|Az-Zukhruf|Ad-Dukhan|Al-Jasiyah|Al-Ahqaf|Muhammad|Al-Fath|Al-Hujurat|Qaf|Az-Zariyat|At-Tur|An-Najm|Al-Qamar|Ar-Rahman|Al-Waqi'ah|Al-Hadid|Al-Mujadalah|Al-Hasyr|Al-Mumtahanah|As-Saff|Al-Jumu'ah|Al-Munafiqun|At-Tagabun|At-Talaq|At-Tahrim|Al-Mulk|Al-Qalam|Al-Haqqah|Al-Ma'arij|Nuh|Al-Jinn|Al-Muzzammil|Al-Muddassir|Al-Qiyamah|Al-Insan|Al-Mursalat|An-Naba'|An-Nazi'at|'Abasa|At-Takwir|Al-Infitar|Al-Mutaffifin|Al-Insyiqaq|Al-Buruj|At-Tariq|Al-A'la|Al-Gasyiyah|Al-Fajr|Al-Balad|Asy-Syams|Al-Lail|Ad-Duha|Asy-Syarh|At-Tin|Al-'Alaq|Al-Qadr|Al-Bayyinah|Az-Zalzalah|Al-'Adiyat|Al-Qari'ah|At-Takasur|Al-'Asr|Al-Humazah|Al-Fil|Quraisy|Al-Ma'un|Al-Kausar|Al-Kafirun|An-Nasr|Al-Masad|Al-Ikhlas|Al-Falaq|An-Nas".split('|');
const ARTI="Pembukaan|Sapi Betina|Keluarga Imran|Wanita|Hidangan|Binatang Ternak|Tempat Tertinggi|Rampasan Perang|Pengampunan|Yunus|Hud|Yusuf|Guruh|Ibrahim|Al-Hijr|Lebah|Perjalanan Malam|Gua|Maryam|Ta Ha|Para Nabi|Haji|Orang-Orang Mukmin|Cahaya|Pembeda|Para Penyair|Semut|Kisah-Kisah|Laba-Laba|Bangsa Romawi|Luqman|Sujud|Golongan yang Bersekutu|Saba'|Pencipta|Yasin|Barisan-Barisan|Sad|Rombongan|Yang Maha Pengampun|Dijelaskan|Musyawarah|Perhiasan|Kabut|Yang Berlutut|Bukit Pasir|Muhammad|Kemenangan|Kamar-Kamar|Qaf|Angin yang Menerbangkan|Bukit|Bintang|Bulan|Yang Maha Pengasih|Hari Kiamat|Besi|Gugatan|Pengusiran|Perempuan yang Diuji|Barisan|Hari Jumat|Orang-Orang Munafik|Hari Dinampakkan Kesalahan|Talak|Pengharaman|Kerajaan|Pena|Hari Kiamat yang Pasti|Tempat Naik|Nuh|Jin|Orang yang Berselimut|Orang yang Berkemul|Hari Kiamat|Manusia|Malaikat yang Diutus|Berita Besar|Malaikat yang Mencabut|Ia Bermuka Masam|Menggulung|Terbelah|Orang-Orang Curang|Terbelah|Gugusan Bintang|Yang Datang di Malam Hari|Yang Paling Tinggi|Hari Pembalasan|Fajar|Negeri|Matahari|Malam|Duha|Kelapangan|Buah Tin|Segumpal Darah|Kemuliaan|Bukti Nyata|Kegoncangan|Kuda Perang|Hari Kiamat|Bermegah-Megahan|Masa|Pengumpat|Gajah|Quraisy|Barang-Barang Berguna|Nikmat yang Banyak|Orang-Orang Kafir|Pertolongan|Gejolak Api|Ikhlas|Waktu Subuh|Manusia".split('|');
const AYAT=[7,286,200,176,120,165,206,75,129,109,123,111,43,52,99,128,111,110,98,135,112,78,118,64,77,227,93,88,69,60,34,30,73,54,45,83,182,88,75,85,54,53,89,59,37,35,38,29,18,45,60,49,62,55,78,96,29,22,24,13,14,11,11,18,12,12,30,52,52,44,28,28,20,56,40,31,50,40,46,42,29,19,36,25,22,17,19,26,30,20,15,21,11,8,8,19,5,8,8,11,11,8,3,9,5,4,7,3,6,3,5,4,5,6];
const JUZ=[[1,1],[2,142],[2,253],[3,93],[4,24],[4,148],[5,82],[6,111],[7,88],[8,41],[9,93],[11,6],[12,53],[15,1],[17,1],[18,75],[21,1],[23,1],[25,21],[27,56],[29,46],[33,31],[36,28],[39,32],[41,47],[46,1],[51,31],[58,1],[67,1],[78,1]];
const MENU={
 wirid:['Wirid harian','Sholawat','Asmaul Husna','Istighasah & mujahadah','Ratib','Hizib','Dalail al-Khairat','Manakib Syekh Abdul Qadir'],
 doa:['Doa keseharian','Doa rezeki','Doa tolak bala','Doa kesehatan','Doa perjalanan','Doa ilmu','Doa waktu tertentu','Doa kualitas diri','Doa pernikahan & rumah tangga','Doa hamil & persalinan','Doa wudu','Doa para nabi di Al-Qur\'an','Doa baca Al-Qur\'an','Doa salat','Doa haji & umrah','Doa kematian'],
 maulid:['Maulid Diba\'i','Maulid Barzanji','Maulid Syarafil Anam','Maulid Simtud Durar','Qasidah Burdah',"Maulid Adl-Dliya'ul Lami'",'Maulid Azab'],
 zakat:[['infak','Infak & sedekah'],['mal','Zakat mal'],['fitrah','Zakat fitrah & fidyah'],['kurban','Kurban'],['koin','Koin Fadzkuruuni'],['galang','Galang dana'],['riwayat','Riwayat pembayaran']]};
const SHORT=[['quran','book',"Al-Qur'an"],['wirid','beads','Wirid & Doa'],['jadwal','mosque','Jadwal Salat'],['kiblat','kaaba','Kiblat'],['tahlil','users','Tahlil & Yasin'],['maulid','moon','Maulid'],['zakat','heart','Zakat & Sedekah'],['menu','grid','Lainnya']];

/* ---------- Jadwal salat (hitungan astronomi, 100% offline; Fajr 20°, Isya 18° ala Kemenag) ---------- */
function waktu(d,{lat,lng,tz:TZ}){
  const r=Math.PI/180,tz=TZ??-d.getTimezoneOffset()/60,n=v=>((v+12)%24+24)%24-12;
  const j=Date.UTC(d.getFullYear(),d.getMonth(),d.getDate(),12)/864e5+2440587.5-2451545;
  const g=(357.529+.98560028*j)*r,q=280.459+.98564736*j,L=(q+1.915*Math.sin(g)+.02*Math.sin(2*g))*r,e=23.439*r;
  const ra=Math.atan2(Math.cos(e)*Math.sin(L),Math.cos(L))/r/15,dec=Math.asin(Math.sin(e)*Math.sin(L));
  const noon=12+tz-lng/15-n(q/15-ra),sL=Math.sin(lat*r),cL=Math.cos(lat*r),sD=Math.sin(dec),cD=Math.cos(dec);
  const h=a=>Math.acos(Math.max(-1,Math.min(1,(Math.sin(a*r)-sL*sD)/(cL*cD))))/r/15;
  const asr=Math.atan(1/(1+Math.tan(Math.abs(lat*r-dec))))/r;
  return [['Subuh',noon-h(-20)],['Terbit',noon-h(-.833)],['Zuhur',noon+.0333],['Asar',noon+h(asr)],['Magrib',noon+h(-.833)+.0333],['Isya',noon+h(-18)]];
}
const hm=h=>{const m=Math.round(((h%24)+24)%24*60)%1440;return String(m/60|0).padStart(2,'0')+':'+String(m%60).padStart(2,'0')};
const hijri=(d=new Date())=>new Intl.DateTimeFormat('id-u-ca-islamic-umalqura',{day:'numeric',month:'long',year:'numeric'}).format(d);

/* ---------- Al-Qur'an (teks diunduh sekali, lalu disimpan Service Worker untuk offline) ---------- */
const qUrl=n=>`https://api.alquran.cloud/v1/surah/${n}/editions/quran-uthmani,id.indonesian,en.transliteration`;
const qGet=async n=>{const r=await fetch(qUrl(n));if(!r.ok)throw 0;const d=(await r.json()).data;return d[0].ayahs.map((a,i)=>({a:a.text,t:d[1].ayahs[i].text,l:d[2]?.ayahs?.[i]?.text||''}))};

/* ---------- Zakat (nisab emas 85 g; hasil bumi 653 kg gabah ~ 5 wasaq; dapat diubah di kode) ---------- */
const NIS=85,RATE=.025;
const gold=()=>+S.gold||0;
const zNet=(label,f1,f2)=>({t:label,f:[['a',f1],['b',f2]],run:v=>{const base=v.a-v.b,nis=NIS*gold();return {base,nis,z:base>=nis&&nis>0?base*RATE:0,info:'Harta bersih = '+rp(base)+'. Nisab = 85 g emas = '+rp(nis)+'. Tarif 2,5% jika sudah genap satu tahun (haul).'}}});
const ZK={
 emas:{t:'Simpanan emas & perak',f:[['a','Emas (gram)'],['b','Perak (gram)'],['c','Harga perak /gram (Rp)']],run:v=>{const e=v.a*gold(),p=v.b*(v.c||0),zE=v.a>=NIS?e*RATE:0,zP=v.b>=595?p*RATE:0;return {base:e+p,nis:NIS*gold(),z:zE+zP,info:'Nisab emas 85 g, perak 595 g; masing-masing dihitung sendiri, tarif 2,5%, haul 1 tahun.'}}},
 dagang:zNet('Perdagangan','Modal + keuntungan + piutang lancar (Rp)','Utang jatuh tempo (Rp)'),
 usaha:zNet('Perusahaan','Aset lancar (Rp)','Kewajiban jangka pendek (Rp)'),
 properti:zNet('Properti (hasil sewa)','Hasil sewa setahun (Rp)','Biaya operasional (Rp)'),
 profesi:{t:'Profesi',f:[['a','Penghasilan per bulan (Rp)'],['b','Penghasilan lain per bulan (Rp)'],['c','Cicilan kebutuhan pokok per bulan (Rp)']],run:v=>{const m=v.a+v.b-v.c,nis=NIS*gold();return {base:m*12,nis,z:m*12>=nis&&nis>0?m*RATE:0,info:'Penghasilan bersih setahun dibandingkan nisab 85 g emas. Bila wajib, zakat per bulan = 2,5% dari penghasilan bersih bulanan.'}}},
 tambak:zNet('Tambak / perikanan','Hasil panen setahun (Rp)','Biaya produksi (Rp)'),
 kebun:{t:'Tanaman produktif',f:[['a','Hasil panen (kg)'],['b','Harga /kg (Rp)'],['r','Biaya perawatan',[['.1','Tanpa biaya (10%)'],['.05','Berbiaya (5%)']]]],run:v=>{const w=v.a>=653,kg=w?v.a*v.r:0;return {base:v.a,nis:653,z:kg*v.b,unit:'kg',kg,info:'Dianalogikan dengan hasil pertanian (nisab 653 kg). Ada perbedaan pendapat ulama; konsultasikan dengan lembaga zakat.'}}},
 ternak:{t:'Peternakan',f:[['r','Jenis ternak',[['1','Kambing / domba'],['2','Sapi / kerbau']]],['a','Jumlah ekor']],run:v=>{const n=v.a;let o='Belum mencapai nisab.',z=0;if(v.r==1){if(n>=40)z=n<=120?'1 ekor kambing (domba 1 th / kambing 2 th)':n<=200?'2 ekor kambing':n<=399?'3 ekor kambing':Math.floor(n/100)+' ekor kambing';if(n>=40)o=''}else{if(n>=30)o=n<40?'1 ekor sapi tabi\' (1 th)':n<60?'1 ekor sapi musinnah (2 th)':n<70?'2 ekor sapi tabi\'':'Hitung: tiap 30 ekor = 1 tabi\', tiap 40 ekor = 1 musinnah'}return {txt:z||o,info:'Nisab kambing 40 ekor, sapi 30 ekor; syarat: mencapai haul dan digembalakan (saimah).'}}},
 tani:{t:'Pertanian tanaman pangan',f:[['a','Hasil panen (kg gabah)'],['b','Harga gabah /kg (Rp)'],['r','Pengairan',[['.1','Tadah hujan (10%)'],['.05','Irigasi berbiaya (5%)'],['.075','Campuran (7,5%)']]]],run:v=>{const w=v.a>=653;const kg=w?v.a*v.r:0;return {base:v.a,nis:653,z:kg*v.b,unit:'kg',kg,info:'Nisab 653 kg gabah (5 wasaq), tanpa haul, dikeluarkan saat panen. Zakat: '+kg.toFixed(2)+' kg.'}}}};

/* ---------- Komponen ---------- */
const list=(a,fn)=>`<div class="list">${a.map(fn).join('')}</div>`;
const head=(t,back='#/',x='')=>`<div class="bar"><a class="bk" href="${back=='back'?'javascript:history.back()':back}" aria-label="Kembali">${ic('back',22)}</a><h1>${t}</h1>${x}</div>`;
const tabs=(a,i=0)=>`<div class="tabs">${a.map((x,k)=>`<button data-tab="${k}" class="${k==i?'on':''}">${x}</button>`).join('')}</div>`;
const soon=a=>list(a,(x,i)=>`<a class="row" href="#/segera/${encodeURIComponent(x)}"><span class="num">${i+1}</span><span class="t">${x}<br><small>Segera hadir</small></span>${ic('next',18)}</a>`);
function twoTabs(t,l,r,A,B,back='#/'){return {html:head(t,back)+tabs([l,r])+`<div id="tb">${A}</div>`,init(){$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.toggle('on',x==b));$('#tb').innerHTML=b.dataset.tab==0?A:B})}}}

/* ---------- Halaman ---------- */
const P={};
const gps=cb=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>{S.loc={lat:p.coords.latitude,lng:p.coords.longitude,n:'Lokasi saya',tz:-new Date().getTimezoneOffset()/60};save();toast('Lokasi diperbarui');cb()},()=>toast('Izin lokasi ditolak. Aktifkan GPS dan izinkan akses.'),{timeout:10000}):toast('Perangkat tidak mendukung lokasi');
P.kiblat=()=>{const r=Math.PI/180,{lat,lng}=S.loc,dl=(39.8262-lng)*r,b=((Math.atan2(Math.sin(dl),Math.cos(lat*r)*Math.tan(21.4225*r)-Math.sin(lat*r)*Math.cos(dl))/r)+360)%360;
 return {html:head('Arah kiblat')+locCard()+`<div class="card" style="text-align:center"><b style="font-size:30px">${b.toFixed(1)}°</b><br><small class="mut">dari utara sejati · ${S.loc.n}</small><div class="needle" id="nd"><i></i></div><p class="mut" id="kh">Atur lokasi lebih dulu, lalu aktifkan kompas dan goyangkan ponsel membentuk angka 8 agar akurat.</p><button class="btn" id="cmp">Aktifkan kompas</button></div>`,
 init(){$('#nd').style.transform=`rotate(${b}deg)`;$('#cmp').onclick=async()=>{try{if(DeviceOrientationEvent.requestPermission&&await DeviceOrientationEvent.requestPermission()!='granted')throw 0}catch(e){return toast('Izin sensor ditolak')}
  const f=e=>{const h=e.webkitCompassHeading??(e.alpha!=null?360-e.alpha:null);if(h==null||!$('#nd'))return;$('#nd').style.transform=`rotate(${b-h}deg)`;$('#kh').textContent='Putar badan hingga panah hijau menghadap ke atas.'};
  addEventListener('deviceorientationabsolute',f,true);addEventListener('deviceorientation',f,true);toast('Kompas aktif')}}}};
P.quran=()=>({html:`<div class="bar"><a class="bk" href="#/">${ic('back',22)}</a><h1>Al-Quran</h1><button class="btn s" onclick="$('#q').focus()">${ic('search',16)} Cari</button></div><input class="in" id="q" type="search" placeholder="Cari surah…">${tabs(['Surah','Juz','Riwayat'])}<div id="ql"></div><div class="card" style="margin-top:16px"><b>Unduh untuk offline</b><p class="mut" style="margin:4px 0 10px">Teks 114 surah dan terjemah diunduh sekali saat online, lalu bisa dibaca tanpa internet.</p><button class="btn" id="dl">Unduh semua surah</button> <small class="mut" id="dp"></small></div>`,
 init(){let tab=0;const draw=()=>{const q=$('#q').value.toLowerCase();let a=NAMA.map((n,i)=>i+1);if(tab==2)a=S.hist;else if(q)a=a.filter(i=>(NAMA[i-1]+i).toLowerCase().includes(q));
  $('#ql').innerHTML=tab==1?list(JUZ,(j,i)=>`<a class="row" href="#/quran/${j[0]}/${j[1]}"><span class="num">${i+1}</span><span class="t">Juz ${i+1}<br><small>${NAMA[j[0]-1]} : ${j[1]}</small></span></a>`):a.length?list(a,i=>`<a class="row" href="#/quran/${i}"><span class="num">${i}</span><span class="t">${NAMA[i-1]}<br><small>${ARTI[i-1]} (${AYAT[i-1]} Ayat)</small></span></a>`):'<div class="card mut">Belum ada riwayat.</div>'};
  $$('[data-tab]').forEach(b=>b.onclick=()=>{tab=+b.dataset.tab;$$('[data-tab]').forEach(x=>x.classList.toggle('on',x==b));draw()});$('#q').oninput=draw;draw();
  $('#dl').onclick=async()=>{$('#dl').disabled=true;let ok=0;for(let i=1;i<=114;i++){try{await qGet(i);ok++}catch(e){}$('#dp').textContent=ok+'/114'}toast(ok==114?'Selesai. Al-Qur\'an siap dibaca offline':'Sebagian gagal, cek internet lalu coba lagi');$('#dl').disabled=false}}});
const surah=(n,sc)=>{n=+n;if(!NAMA[n-1])return P.quran();return {html:`<div class="rh"><a class="bk" href="#/quran" aria-label="Daftar surah">${ic('back',22)}</a><div class="rt"><b>${n}. ${NAMA[n-1]}</b><small>${ARTI[n-1]} · ${AYAT[n-1]} ayat</small></div><button class="ib" id="fsb" aria-label="Layar penuh">${ic('full',20)}</button><button class="ib" id="qs" aria-label="Pengaturan baca">${ic('sliders',20)}</button></div><audio id="au" preload="none" src="https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/${n}.mp3"></audio><div class="pl"><button class="ib" id="pp" aria-label="Putar audio">${ic('play',20)}</button><div class="pb"><i id="pg"></i></div><small class="mut">Audio (butuh internet)</small></div><div id="ay"><p class="mut">Memuat…</p></div><div style="display:flex;gap:8px;margin-top:16px">${n>1?`<a class="btn s" href="#/quran/${n-1}">‹ Sebelumnya</a>`:''}${n<114?`<a class="btn" href="#/quran/${n+1}">Berikutnya ›</a>`:''}</div>`,
 async init(){$('#qs').onclick=qsheet;qplayer();$('#fsb').onclick=()=>{S.full=!S.full;save();document.body.classList.toggle('full',S.full);window.QA&&drawAy($('#ay'),window.QA,n)};S.hist=[n,...S.hist.filter(x=>x!=n)].slice(0,20);save();const el=$('#ay');try{const A=await qGet(n);window.QA=A;drawAy(el,A,n);if(sc)$('#a'+sc)?.scrollIntoView()}catch(e){el.innerHTML='<div class="card">Surah ini belum tersimpan di perangkat dan internet tidak tersedia. Sambungkan internet sekali, atau unduh semua dari menu Al-Qur\'an.</div>'}}}};
const card=x=>`<div class="card" style="margin-bottom:10px"><b>${x[0]}</b>${x[1]?`<div class="ar2">${x[1]}</div>`:''}${x[2]?`<p style="margin:6px 0 0">${x[2]}</p>`:''}${x[3]?`<a class="btn s" style="display:inline-block;margin-top:8px" href="${x[3]}">${/^http/.test(x[3])?'Buka di ':'Buka'}</a>`:''}</div>`;
const WN=MENU.wirid;
P.wirid=()=>twoTabs('Wirid & Doa','Wirid','Doa',catList('w',WN,WD),catList('d',MENU.doa,DD));
P.doa=P.wirid;


const zhome=()=>({html:head('Zakat & sedekah')+tabs(['Menu','Kalkulator'])+`<div id="tb"></div>`,init(){const A=list(MENU.zakat,(m,i)=>`<a class="row" href="#/sedekah/${m[0]}"><span class="num">${i+1}</span><span class="t">${m[1]}</span>${ic('next',18)}</a>`),B=list(Object.entries(ZK),([k,z])=>`<a class="row" href="#/zakat/${k}"><span class="t">${z.t}</span>›</a>`)+'';const t=$('#tb');t.innerHTML=A;$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.toggle('on',x==b));t.innerHTML=b.dataset.tab==0?A:B})}});
P.zakat=k=>{const z=ZK[k];if(!z)return zhome();return {html:head('Kalkulator zakat','#/zakat')+chips(k)+`<h2 style="color:var(--ink);margin:6px 0 10px">${z.t}</h2>`+`<label>Harga emas /gram (Rp), dipakai semua kalkulator</label><input class="in" id="gold" inputmode="numeric" value="${S.gold}" placeholder="mis. 1500000">`+z.f.map(f=>`<label>${f[1]}</label>`+(f[2]?`<select class="in" data-f="${f[0]}">${f[2].map(o=>`<option value="${o[0]}">${o[1]}</option>`).join('')}</select>`:`<input class="in" data-f="${f[0]}" inputmode="decimal" placeholder="0">`)).join('')+`<div class="res" id="rs">Isi data di atas.</div>`,
 init(){$('.chip2.on')?.scrollIntoView({inline:'center',block:'nearest'});const calc=()=>{S.gold=$('#gold').value.replace(/\D/g,'');save();const v={};$$('[data-f]').forEach(i=>v[i.dataset.f]=parseFloat(i.value.replace(',','.'))||0);if(!['tani','kebun','ternak'].includes(k)&&!gold())return $('#rs').textContent='Isi harga emas per gram terlebih dahulu.';const r=z.run(v);if(r.txt)return $('#rs').innerHTML=`<b>${r.txt}</b><br><small class="mut">${r.info}</small>`;$('#rs').innerHTML=(r.z>0?`Wajib zakat<br><b>${r.unit?r.kg.toFixed(2)+' kg · ':''}${rp(r.z)}</b>`:`<b>Belum wajib zakat</b>`)+`<br><small class="mut">${r.info}</small>`};$$('input,select').forEach(i=>i.oninput=calc);calc()}}};



/* ---------- Beranda & kalender bergaya aplikasi ---------- */
const PAS=['Legi','Pahing','Pon','Wage','Kliwon'],HARI=['Ahad','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'];
const pas=(y,m,d)=>PAS[((Math.floor(Date.UTC(y,m,d)/864e5)-Math.floor(Date.UTC(2026,9,7)/864e5))%5+6)%5];
const hf=(d,o)=>new Intl.DateTimeFormat('id-u-ca-islamic-umalqura',o).format(d);
const CARI=[...NAMA.map((n,i)=>[n+' (surah)','#/quran/'+(i+1)]),...[...MENU.wirid,...MENU.doa,...MENU.maulid].map(x=>[x,null])];
/* ---------- Halaman tambahan ---------- */
const doaCards=()=>DOA.map(d=>`<div class="card" style="margin-bottom:10px"><b>${d.j}</b><div class="ar2">${d.a}</div><p class="mut" style="margin:0"><i>${d.l}</i></p><p style="margin:6px 0 0">${d.t}</p>${d.s?`<small class="mut">${d.s}</small>`:''}</div>`).join('');
const ART=[{t:'Panduan zakat fitrah',g:'Zakat',b:'Zakat fitrah wajib bagi setiap muslim yang mampu pada akhir Ramadan, termasuk anggota keluarga yang ditanggung. Ukurannya satu sha\' makanan pokok, yang di Indonesia umumnya dihitung sekitar 2,5 kg beras per jiwa atau senilai uangnya. Dianjurkan ditunaikan sebelum salat Idulfitri. Rujuk ketetapan lembaga zakat setempat untuk nilai rupiah tahun berjalan.'},{t:'Dzikir setelah salat fardu',g:'Wirid',b:'Amalan yang masyhur setelah salat fardu: istighfar tiga kali, lalu tasbih (Subhanallah), tahmid (Alhamdulillah), dan takbir (Allahu Akbar) masing-masing 33 kali, kemudian menggenapkan seratus dengan tahlil. Gunakan menu Tasbih untuk membantu menghitung.'}];
const MENUALL=[['Ibadah',[['quran','book',"Al-Qur'an"],['wirid','beads','Wirid & Doa'],['jadwal','mosque','Jadwal Salat'],['kiblat','kaaba','Kiblat'],['tahlil','users','Tahlil & Yasin'],['maulid','moon','Maulid'],['tasbih','count','Tasbih'],['asma','star','Asmaul Husna']]],['Keuangan',[['zakat','heart','Zakat & Sedekah'],['zakat/emas','scale','Kalkulator Zakat'],['waris','scale','Waris']]],['Belajar',[['kitab','lib','Kitab Kuning'],['artikel','news','Artikel'],['hadits','book','Hadits Nabi'],['mutiara','star','Kata Mutiara']]],['Lainnya',[['kalender','cal','Kalender'],['bookmark','star','Penanda'],['pengaturan','sliders','Pengaturan'],['tentang','info','Tentang']]]];
P.menu=()=>({html:head('Semua Menu')+MENUALL.map(g=>`<h2>${g[0]}</h2><div class="grid g2">${g[1].map(m=>`<a href="#/${m[0]}"><b>${ic(m[1],26)}</b>${m[2]}</a>`).join('')}</div>`).join('')});
P.kitab=i=>i!=null&&KITAB[i]?{html:head(KITAB[i][0],'#/kitab')+`<p class="mut">${KITAB[i][1]} · ${KITAB[i][2]}</p><div class="card"><div class="ar2">${KSAMPLE[0]}</div><b>Terjemahan / makna gandul</b><p>${KSAMPLE[1]}</p></div><p class="mut">Isi lengkap kitab segera hadir.</p>`}:{html:head('Kitab Kuning')+list(KITAB,(k,i)=>`<a class="row" href="#/kitab/${i}"><span class="num">${i+1}</span><span class="t">${k[0]}<br><small>${k[1]} · ${k[2]}</small></span>${ic('next',18)}</a>`)};

P.artikel=i=>i!=null&&ART[i]?{html:head(ART[i].t,'#/artikel')+`<span class="chip">${ART[i].g}</span><p>${ART[i].b}</p>`}:{html:`<h1>Artikel</h1>`+artList()};
const artList=()=>list(ART,(a,i)=>`<a class="row" href="#/artikel/${i}"><span class="t"><span class="chip">${a.g}</span><br>${a.t}</span>${ic('next',18)}</a>`);
/* ---------- Beranda ---------- */
const SK='<svg class="sk" viewBox="0 0 300 40" preserveAspectRatio="none"><path d="M0 40V30h28v-8l3-6 3 6v8h22c0-12 12-18 22-18s22 6 22 18h26v-6h10v-10l4-6 4 6v10h10v6h22v16z" fill="rgba(255,255,255,.12)"/></svg>';
P['']=()=>({html:`<div class="top"><span class="bn"><img src="img/logo.png" alt="" width="44" height="44">Fadzkuruuni</span><a href="#/jadwal">${ic('pin',16)} ${S.loc.n} <b>(Ganti)</b></a></div>${S.nb?'':NOTE}${GREET()}<div class="hero">${SK}<small id="nl"></small><div class="big" id="np">--</div><div id="cd" class="mut2"></div><small>${new Date().toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'})} / ${hf(new Date(),{day:'numeric',month:'long',year:'numeric'})}</small><div class="qt"><span id="qtx"></span></div><div class="pt" id="pt"></div></div>
 <div class="grid g2">${SHORT.map(s=>`<a href="#/${s[0]}"><b>${ic(s[1],26)}</b>${s[2]}</a>`).join('')}</div>
 <div class="srch">${ic('search',18)}<input id="sr" type="search" placeholder="Cari doa, wirid, surah"></div><div id="sl"></div>
 <div class="car"><a class="sl" href="#/zakat/emas"><b>Hitung zakatmu</b><span>6 kalkulator fikih, hasil langsung dalam rupiah</span></a><a class="sl s2" href="#/tahlil"><b>Tahlil &amp; Yasin</b><span>Baca Surah Yasin lengkap, bisa offline</span></a><a class="sl s3" href="#/waris"><b>Kalkulator waris</b><span>Simulasi pembagian harta pusaka</span></a></div>
 ${S.hist[0]?`<h2>Lanjutkan membaca</h2><a class="card" style="display:flex;gap:12px;align-items:center" href="#/quran/${S.hist[0]}">${ic('book',22)}<span>${NAMA[S.hist[0]-1]}<br><small class="mut">${ARTI[S.hist[0]-1]} · ${AYAT[S.hist[0]-1]} ayat</small></span></a>`:''}<h2>Headline</h2>${artList()}`,
 init(){qrot();$('#sr').oninput=e=>{const q=e.target.value.trim().toLowerCase();$('#sl').innerHTML=q?list(CARI.filter(x=>x[0].toLowerCase().includes(q)).slice(0,8),x=>x[1]?`<a class="row" href="${x[1]}"><span class="t">${x[0]}</span>${ic('next',18)}</a>`:`<div class="row" data-soon><span class="t">${x[0]}<br><small>Segera hadir</small></span></div>`):'';$$('[data-soon]').forEach(e=>e.onclick=()=>toast('Konten ini segera hadir'))};
 const tick=()=>{if(!$('#pt'))return clearInterval(P.tk);const now=new Date(),T=waktu(now,S.loc),c=locNow(),idx=T.findIndex((x,i)=>i!=1&&x[1]>c),k=idx<0?0:idx;let df=T[k][1]-c;if(idx<0)df+=24;const D=Math.max(0,Math.round(df*3600)),z=v=>String(v).padStart(2,'0');
  $('#nl').textContent=T[k][0];$('#np').innerHTML=hm(T[k][1])+' <small>'+tzl()+'</small>';$('#cd').textContent='- '+z(D/3600|0)+':'+z(D%3600/60|0)+':'+z(D%60);$('#pt').innerHTML=T.map((x,i)=>`<div class="${i==k?'n':''}">${x[0]}<b>${hm(x[1])}</b></div>`).join('')};tick();clearInterval(P.tk);P.tk=setInterval(tick,1000)}});
/* ---------- Kalender ---------- */

/* ---------- Panel pengaturan baca & gestur ---------- */
function qsheet(cb){const e=document.createElement('div');e.className='back-d';e.innerHTML=`<div class="sheet" role="dialog" aria-label="Pengaturan baca"><b>Pengaturan Al-Qur'an</b><div class="sw">Tampilkan terjemah<input type="checkbox" id="s1" ${S.tr?'checked':''}></div><div class="sw">Tampilkan Latin<input type="checkbox" id="s5" ${S.lt?'checked':''}></div><div class="sw">Ukuran huruf Arab<input type="range" id="s2" min="22" max="52" value="${S.fs}"></div><div class="sw">Mode layar penuh<input type="checkbox" id="s3" ${S.full?'checked':''}></div><button class="btn" id="s4" style="width:100%;margin-top:10px">Selesai</button></div>`;document.body.append(e);
 e.onclick=x=>{if(x.target==e||x.target.id=='s4'){e.remove();cb&&cb()}};$('#s1',e).onchange=x=>{S.tr=x.target.checked;save();$$('.ay .tr').forEach(p=>p.hidden=!S.tr)};$('#s5',e).onchange=x=>{S.lt=x.target.checked;save();$$('.ay .lt').forEach(p=>p.hidden=!S.lt)};$('#s2',e).oninput=x=>{S.fs=+x.target.value;save();$$('.ay .ar').forEach(a=>a.style.fontSize=S.fs+'px')};$('#s3',e).onchange=x=>{S.full=x.target.checked;save();document.body.classList.toggle('full',S.full);window.QA&&drawAy($('#ay'),window.QA,+location.hash.split('/')[2])}}
let tx=0,ty=0;addEventListener('touchstart',e=>{tx=e.touches[0].clientX;ty=e.touches[0].clientY},{passive:true});
addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-tx,dy=e.changedTouches[0].clientY-ty;if(Math.abs(dx)<70||Math.abs(dy)>50||e.target.closest('input,.cal,.car'))return;const T=$$('[data-tab]'),h=location.hash.split('/');
 if(T.length>1){const i=T.findIndex(b=>b.classList.contains('on'));T[i+(dx<0?1:-1)]?.click()}else if(h[1]=='quran'&&h[2]){const n=+h[2]+(dx<0?1:-1);if(n>=1&&n<=114)location.hash='#/quran/'+n}},{passive:true});


/* ---------- Zakat, infak, kurban, riwayat ---------- */
const BANK=[['BSI','7283603126'],['Dana','089652243480'],['GoPay','089652243480'],['OVO','030037791453'],['SeaBank','901696052778'],['Bank Saqu','10088196215']];
const REK=`<div class="card" style="margin-top:12px" data-pay><b>Pilih metode pembayaran</b><p class="mut" style="margin:2px 0 8px">Atas nama Muhammad Hilmi Azkia Rahman</p>${BANK.map((b,i)=>`<label class="pm"><input type="radio" name="pm" value="${i}" ${i?'':'checked'}><span class="t">${b[0]}<br><b>${b[1]}</b></span><button type="button" class="btn s" data-copy="${b[1]}">Salin</button></label>`).join('')}<input class="in" data-nom inputmode="numeric" placeholder="Nominal (opsional)" style="margin-top:10px"><button type="button" class="btn" style="width:100%" data-lanjut>Lanjut pembayaran</button></div>`;
const NIAT='نَوَيْتُ أَنْ أُخْرِجَ زَكَاةَ الْفِطْرِ عَنْ نَفْسِي فَرْضًا لِلّٰهِ تَعَالَى';
const FIT=`<div class="card" data-calc="fitrah" style="margin-top:12px"><b>Hitung zakat fitrah</b><label style="margin-top:8px">Jumlah jiwa</label><input class="in" data-k="j" inputmode="numeric" value="1"><label>Harga beras per kg (Rp)</label><input class="in" data-k="h" inputmode="numeric" placeholder="mis. 15000"><div class="res cres">Isi harga beras per kg.</div><small class="mut">Per jiwa 2,5 kg makanan pokok.</small></div>`;
const FID=`<div class="card" data-calc="fidyah" style="margin-top:12px"><b>Hitung fidyah</b><label style="margin-top:8px">Jumlah orang</label><input class="in" data-k="j" inputmode="numeric" value="1"><label>Jumlah hari puasa yang ditinggalkan</label><input class="in" data-k="d" inputmode="numeric" value="1"><label>Harga makanan pokok per kg (Rp)</label><input class="in" data-k="h" inputmode="numeric" placeholder="mis. 15000"><div class="res cres">Isi harga makanan pokok per kg.</div><small class="mut">Per hari 0,6 kg (satu mud).</small></div>`;
const SD={infak:['Infak & sedekah','Infak dan sedekah tidak mengenal nisab maupun waktu tertentu. Berikan sebagian rezeki untuk yang membutuhkan, sekecil apa pun, dan lakukan dengan ikhlas.'+REK],
 mal:['Zakat mal','Zakat harta wajib bila mencapai nisab dan haul. Hitung kewajibanmu di menu Kalkulator Zakat, lalu salurkan melalui rekening di bawah.<br><a class="btn" style="display:inline-block;margin-top:10px" href="#/zakat">Buka kalkulator</a>'+REK],
 kurban:['Kurban','Kurban disembelih pada Iduladha dan hari tasyrik. Kambing atau domba untuk satu orang; sapi atau kerbau boleh patungan tujuh orang. Hewan harus sehat, cukup umur, dan tidak cacat.'+REK],
 koin:['Koin Fadzkuruuni','Program koin sedekah harian Fadzkuruuni akan segera hadir.'],
 galang:['Galang dana','Program galang dana akan segera hadir. Kabar terbaru akan ditampilkan di sini.']};
P.sedekah=k=>{if(k=='fitrah')return twoTabs('Zakat fitrah & fidyah','Zakat fitrah','Fidyah puasa',`<div class="card"><b>Ketentuan</b><p>Wajib bagi setiap muslim, termasuk yang ditanggung, pada akhir Ramadan. Ukurannya satu sha' makanan pokok, sekitar 2,5 kg beras per jiwa atau senilai uangnya. Dianjurkan ditunaikan sebelum salat Idulfitri.</p><b>Niat untuk diri sendiri</b><div class="ar2">${NIAT}</div></div>`+FIT+REK,`<div class="card"><b>Fidyah</b><p>Fidyah diberikan oleh yang tidak mampu berpuasa dan tidak dapat mengganti, misalnya karena sakit menahun atau usia lanjut. Ukurannya satu mud (sekitar 0,6 kg) makanan pokok untuk setiap hari yang ditinggalkan, diberikan kepada fakir miskin.</p></div>`+FID+REK,'#/zakat');
 if(k=='riwayat')return {html:head('Riwayat pembayaran','#/zakat')+`<select class="in" id="pj"><option>Zakat fitrah</option><option>Zakat mal</option><option>Infak & sedekah</option><option>Kurban</option><option>Fidyah</option></select><input class="in" id="pn" inputmode="numeric" placeholder="Nominal (Rp)"><button class="btn" id="ps" style="width:100%">Catat pembayaran</button><div id="pl" style="margin-top:12px"></div>`,init(){S.pay=S.pay||[];const d=()=>$('#pl').innerHTML=S.pay.length?list(S.pay,(x,i)=>`<div class="row"><span class="t">${x.j}<br><small>${x.d}</small></span><b>${rp(x.n)}</b><button class="btn s" data-x="${i}">${ic('back',14)}</button></div>`):'<div class="card mut">Belum ada catatan pembayaran. Catatan hanya tersimpan di perangkat ini.</div>';d();$('#ps').onclick=()=>{const n=+$('#pn').value.replace(/\D/g,'');if(!n)return toast('Isi nominal');S.pay.unshift({j:$('#pj').value,n,d:new Date().toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'})});save();$('#pn').value='';d()};$('#pl').onclick=e=>{const b=e.target.closest('[data-x]');if(b){S.pay.splice(+b.dataset.x,1);save();d()}}}};
 const x=SD[k];return x?{html:head(x[0],'#/zakat')+`<div class="card">${x[1]}</div>`}:zhome()};


/* ---------- Penanda ayat & salin ---------- */

document.addEventListener('click',e=>{const c=e.target.closest('[data-copy]');if(c){const v=c.dataset.copy;(navigator.clipboard?navigator.clipboard.writeText(v):Promise.reject()).then(()=>toast(v.length>30?'Teks disalin':'Disalin: '+v),()=>toast('Tidak bisa menyalin. Salin manual.'));return}
 const b=e.target.closest('[data-bm]');if(b){const k=b.dataset.bm;S.bm=S.bm||[];const i=S.bm.indexOf(k);i<0?S.bm.unshift(k):S.bm.splice(i,1);save();b.classList.toggle('on',i<0);toast(i<0?'Ayat ditandai':'Penanda dihapus')}});


/* ---------- Adzan & notifikasi ---------- */
const WS=['Subuh','Zuhur','Asar','Magrib','Isya'],WI=[0,2,3,4,5];
S.az=Object.assign({on:false,sound:true,pre:0,w:[1,1,1,1,1]},S.az||{});
const beep=()=>{try{const c=new(window.AudioContext||window.webkitAudioContext)(),t=c.currentTime;[0,.35,.7].forEach(d=>{const o=c.createOscillator(),g=c.createGain();o.frequency.value=660;o.connect(g);g.connect(c.destination);g.gain.setValueAtTime(.2,t+d);g.gain.exponentialRampToValueAtTime(.001,t+d+.3);o.start(t+d);o.stop(t+d+.3)})}catch(e){}};
let ADZ=null;const stopAdzan=()=>{if(ADZ){ADZ.pause();ADZ=null}};const play=(k=1)=>{if(!S.az.sound)return;stopAdzan();ADZ=new Audio(k==0?'audio/adzan-subuh.mp3':'audio/adzan.mp3');ADZ.onerror=beep;ADZ.play?.().catch(beep)};
const notify=async(t,b)=>{if(!('Notification'in window)||Notification.permission!='granted')return;try{const r=await navigator.serviceWorker.ready;r.showNotification(t,{body:b,icon:'img/icon-192.png',badge:'img/icon-192.png',tag:'adzan',vibrate:[200,100,200]})}catch(e){new Notification(t,{body:b})}};
const askNotif=async()=>{if(!('Notification'in window)){toast('Browser tidak mendukung notifikasi');return false}const r=await Notification.requestPermission();toast(r=='granted'?'Notifikasi diizinkan':'Izin ditolak. Aktifkan lewat pengaturan situs di browser.');return r=='granted'};
let fired='';
setInterval(()=>{if(!S.az.on)return;const n=new Date(),T=waktu(n,S.loc),mm=Math.floor(locNow()*60),pre=+S.az.pre;WI.forEach((wi,k)=>{if(!S.az.w[k])return;const m=Math.round(T[wi][1]*60)%1440;[[m-pre,1],[m,0]].forEach(([x,isPre])=>{if(isPre&&!pre)return;const key=n.toDateString()+WS[k]+isPre;if(x==mm&&!fired.includes(key)){fired+=key+'|';isPre?notify('Menjelang '+WS[k],pre+' menit lagi masuk waktu '+WS[k]+' ('+S.loc.n+')'):(notify('Waktu '+WS[k]+' telah tiba','Untuk wilayah '+S.loc.n+' dan sekitarnya'),play(k))}})})},5000);
/* ---------- Pengaturan ---------- */
const row=(i,t,sb,r)=>`<div class="srw"><span class="si">${ic(i,20)}</span><span class="t">${t}${sb?`<br><small class="mut">${sb}</small>`:''}</span>${r}</div>`;
const tg=(id,on)=>`<label class="tg"><input type="checkbox" id="${id}" ${on?'checked':''}><i></i></label>`;
const lk=(h,i,t)=>`<a class="srw" href="${h}"><span class="si">${ic(i,20)}</span><span class="t">${t}</span>${ic('next',18)}</a>`;
P.pengaturan=()=>({html:`<h1>Pengaturan</h1>${AKUN()}${PROFIL()}<h2>Tampilan</h2><div class="list sg">
${row('moon','Tema','Pilih tampilan aplikasi','')}<div class="segw">${seg('th',[['auto','Perangkat'],['light','Terang'],['dark','Gelap']],S.theme)}</div>
${row('book','Ukuran huruf Arab','',`<input type="range" id="fs" min="22" max="52" value="${S.fs}">`)}
${row('search','Tampilkan Latin','Transliterasi di bawah ayat',tg('lt',S.lt))}
${row('news','Tampilkan terjemah','',tg('tr',S.tr))}${row('count','Tasbih melayang','Tombol hitung kecil di semua halaman',tg('fb',S.ft!==false))}</div>
${IZIN()}<h2>Waktu salat & adzan</h2><div class="list sg">
${row('pin','Lokasi',`${S.loc.n} (${S.loc.lat.toFixed(2)}, ${S.loc.lng.toFixed(2)})`,'<button class="btn s" id="gp">Perbarui</button>')}
${row('bell','Pengingat adzan','Notifikasi saat waktu salat tiba',tg('ao',S.az.on))}
${row('bell','Suara adzan','Memutar adzan (Subuh memakai suara berbeda); nada bawaan bila file belum ada',tg('as',S.az.sound))}
${row('clock','Pengingat sebelum adzan','Notifikasi beberapa menit sebelum waktu salat','')}<div class="segw">${seg('ap',[[0,'Mati'],[5,'5 mnt'],[10,'10 mnt'],[15,'15 mnt']],S.az.pre)}</div>
${row('bell','Tes notifikasi & suara','Pastikan izin dan suara berfungsi','<button class="btn s" id="at">Tes</button> <button class="btn s" data-tsub>Subuh</button> <button class="btn s" data-stop>Stop</button>')}</div>
<h2>Notifikasi per waktu</h2><div class="list sg">${WS.map((w,k)=>row('clock',w,'',tg('aw'+k,S.az.w[k]))).join('')}</div>
${OFFL()}<h2>Data</h2><div class="list sg">${lk('#/bookmark','star','Daftar penanda ayat')}${lk('#/quran','book',"Unduh Al-Qur'an untuk offline")}${row('back','Hapus riwayat bacaan','','<button class="btn s" id="hx">Hapus</button>')}</div>
<h2>Lainnya</h2><div class="list sg">${lk('#/tentang','info','Tentang aplikasi')}</div>
<p class="mut" style="text-align:center;margin-top:16px">Adzan dan pengingat berbunyi saat aplikasi terbuka atau terpasang dan berjalan. Untuk bunyi saat aplikasi tertutup penuh dibutuhkan aplikasi native.</p>`,
 init(){permFill();offFill();segBind('th',v=>{S.theme=v;save();theme()});segBind('ap',v=>{S.az.pre=+v;save()});$('#fs').oninput=e=>{S.fs=+e.target.value;save()};$('#lt').onchange=e=>{S.lt=e.target.checked;save()};$('#tr').onchange=e=>{S.tr=e.target.checked;save()};$('#fb').onchange=e=>{S.ft=e.target.checked;save();ftUpd()};$('#gp').onclick=()=>gps(route);
 $('#ao').onchange=async e=>{if(e.target.checked&&!await askNotif()){e.target.checked=false}S.az.on=e.target.checked;save()};$('#as').onchange=e=>{S.az.sound=e.target.checked;save()};
 WS.forEach((w,k)=>$('#aw'+k).onchange=e=>{S.az.w[k]=+e.target.checked;save()});
 $('#at').onclick=async()=>{if(await askNotif()){notify('Tes notifikasi','Pengingat adzan Fadzkuruuni berfungsi.');play()}};$('#hx').onclick=()=>{S.hist=[];save();toast('Riwayat dihapus')}}});


/* ---------- Komponen baru: segmen, stepper, chip ---------- */
const seg=(id,o,v)=>`<div class="seg" id="${id}">${o.map(x=>`<button type="button" data-v="${x[0]}" class="${x[0]==v?'on':''}">${x[1]}</button>`).join('')}</div>`;
const segBind=(id,fn)=>$$('#'+id+' button').forEach(b=>b.onclick=()=>{$$('#'+id+' button').forEach(x=>x.classList.toggle('on',x==b));fn(b.dataset.v)});
const stp=(k,v,max)=>`<span class="stp" data-k="${k}" data-max="${max}"><button type="button" data-s="-1" aria-label="Kurangi">−</button><b>${v}</b><button type="button" data-s="1" aria-label="Tambah">+</button></span>`;
const chips=k=>`<div class="chips">${Object.entries(ZK).map(([i,z])=>`<a class="chip2 ${i==k?'on':''}" href="#/zakat/${i}">${z.t}</a>`).join('')}</div>`;
P.segera=t=>({html:head(decodeURIComponent(t||''),'back')+`<div class="card"><b>Teks belum tersedia</b><p class="mut" style="margin:6px 0 0">Bacaan ini belum dimuat di aplikasi karena teks dan izin penggunaannya masih disiapkan. Bacaan yang sudah lengkap bisa dibuka dari menu Wirid &amp; Doa.</p></div>`});
document.addEventListener('input',e=>{const c=e.target.closest('[data-calc]');if(!c)return;const g=k=>parseFloat((c.querySelector(`[data-k=${k}]`)?.value||'').replace(',','.'))||0,o=c.querySelector('.cres'),t=c.dataset.calc;if(!g('h'))return o.textContent='Isi harga per kg terlebih dahulu.';const kg=t=='fitrah'?g('j')*2.5:g('j')*g('d')*.6;o.innerHTML=`<b>${rp(kg*g('h'))}</b><br><small class="mut">${kg.toFixed(2).replace('.',',')} kg makanan pokok</small>`});
/* ---------- Tahlil & Yasin (teks Al-Qur'an tampil langsung di halaman) ---------- */
const AY=async(n,a,b)=>{const A=await qGet(n);return A.slice(a?a-1:0,b||A.length).map((x,i)=>`<div class="ay2"><span class="n">${(a||1)+i}</span><div class="ar" style="font-size:${S.fs}px">${x.a}</div>${S.lt&&x.l?`<p class="lt">${x.l}</p>`:''}${S.tr?`<p class="mut" style="margin:4px 0 0">${x.t}</p>`:''}</div>`).join('')};
const TREF={'Hadiah Al-Fatihah':[[1,0,0,'']],'Al-Ikhlas, Al-Falaq, An-Nas':[[112,0,0,'Al-Ikhlas (dibaca 3×)'],[113,0,0,'Al-Falaq'],[114,0,0,'An-Nas']],'Ayat Kursi':[[2,255,255,'']],'Akhir Surah Al-Baqarah':[[2,285,286,'']]};
const tahlilHtml=()=>TH.filter(x=>x[0]!='Surah Yasin'&&(x[1]||TREF[x[0]])).map(x=>`<h3 class="sec">${x[0]}</h3>${x[1]?`<div class="ar2">${x[1]}</div>`:''}${TREF[x[0]]?TREF[x[0]].map(r=>(r[3]?`<h4 class="sub">${r[3]}</h4>`:'')+`<div data-ref="${r[0]}:${r[1]}:${r[2]}"></div>`).join(''):`<p class="mut">${x[2]}</p>`}`).join('');
P.tahlil=()=>({html:head('Tahlil & Yasin','#/',RS)+tabs(['Tahlil','Yasin'])+zoomBar()+'<div id="tb"></div>',init(){let tok=0;const show=async k=>{const t=$('#tb'),my=++tok;t.innerHTML=k?'<p class="mut">Memuat Surah Yasin…</p>':tahlilHtml();try{if(k){const h='<h3 class="sec">Surah Yasin</h3>'+await AY(36);if(my==tok)t.innerHTML=h}else for(const e of $$('[data-ref]',t)){const [n,a,b]=e.dataset.ref.split(':').map(Number);const h=await AY(n,a,b);if(my!=tok)return;e.innerHTML=h}}catch(x){if(my==tok)t.insertAdjacentHTML('beforeend','<div class="card mut" style="margin-top:12px">Teks Al-Qur\'an belum tersimpan di perangkat. Sambungkan internet sekali, atau unduh dari menu Al-Qur\'an.</div>')}};$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.toggle('on',x==b));show(+b.dataset.tab)});show(0)}});
/* ---------- Penanda ayat ---------- */
P.bookmark=()=>({html:head('Penanda ayat')+`<p class="mut">Penanda menyimpan ayat yang ingin kamu baca lagi. Ketuk ikon bintang pada sebuah ayat saat membaca, lalu temukan semuanya di sini.</p><div id="bl"></div>`,
 init(){const B=S.bm||[],el=$('#bl');if(!B.length){el.innerHTML='<div class="card mut">Belum ada penanda. Buka sebuah surah, lalu ketuk ikon bintang pada ayat.</div>';return}
  el.innerHTML=list(B,k=>{const [n,a]=k.split(':');return `<div class="row"><a class="t" href="#/quran/${n}/${a}" style="flex:1;min-width:0"><b>${NAMA[n-1]}</b> · ayat ${a}<br><small data-s="${k}">${ARTI[n-1]}</small></a><button class="btn s" data-x="${k}">Hapus</button></div>`});
  B.forEach(k=>{const [n,a]=k.split(':');qGet(+n).then(A=>{const e=$(`[data-s="${k}"]`);if(e&&A[a-1])e.textContent=A[a-1].t.slice(0,90)+'…'}).catch(()=>{})});
  el.onclick=e=>{const b=e.target.closest('[data-x]');if(b){S.bm=S.bm.filter(x=>x!=b.dataset.x);save();route()}}}});
/* ---------- Waris (faraidh) lengkap: pasangan, keturunan, orang tua, kakek-nenek, saudara ---------- */
const WH=[['son','Anak laki-laki',99],['dau','Anak perempuan',99],['gson','Cucu laki-laki (dari anak laki-laki)',99],['gdau','Cucu perempuan (dari anak laki-laki)',99],['fa','Ayah',1],['mo','Ibu',1],['gf','Kakek (dari ayah)',1],['gm','Nenek',1],['fb','Saudara laki-laki kandung',99],['fs','Saudara perempuan kandung',99],['pb','Saudara laki-laki seayah',99],['ps','Saudara perempuan seayah',99],['ms','Saudara seibu (laki-laki/perempuan)',99]];
function faraidh(v){const F=[],A=[],N=[],c=k=>v[k]||0,add=(n,f)=>F.push({n,f}),lb=(n,k)=>k>1?`${n} (${k} orang)`:n;
 const gA=!c('son'),desc=c('son')||c('dau')||(gA&&(c('gson')||c('gdau'))),mD=c('son')||(gA&&c('gson')),fD=c('dau')||(gA&&c('gdau')),faA=c('fa')>0,gfA=c('gf')>0&&!faA,asc=faA||gfA,sib=c('fb')+c('fs')+c('pb')+c('ps')+c('ms');let sp=0;
 if(v.sp=='suami'){sp=desc?1/4:1/2;add('Suami',sp)}if(v.sp=='istri'){sp=desc?1/8:1/4;add(lb('Istri',c('ni')),sp)}
 if(c('mo'))add('Ibu',(desc||sib>=2)?1/6:((v.sp&&faA&&sib<2)?(1-sp)/3:1/3));
 if(c('gm')&&!c('mo'))add('Nenek',1/6);
 if(asc){const nm=faA?'Ayah':'Kakek';if(mD)add(nm,1/6);else if(desc){add(nm,1/6);A.push({p:3,m:[[nm,1,1]]})}else A.push({p:3,m:[[nm,1,1]]});if(gfA&&c('fb')+c('fs')+c('pb')+c('ps'))N.push('Kakek bersama saudara kandung/seayah dihitung seperti ayah (saudara terhalang). Pendapat lain membagi bersama saudara; konsultasikan ke ahli faraidh.')}
 if(c('son'))A.push({p:1,m:[['Anak laki-laki',c('son'),2],['Anak perempuan',c('dau'),1]]});else if(c('dau'))add(c('dau')>1?`Anak perempuan (${c('dau')} orang)`:'Anak perempuan',c('dau')>1?2/3:1/2);
 if(gA&&(c('gson')||c('gdau'))){if(c('gson'))A.push({p:2,m:[['Cucu laki-laki',c('gson'),2],['Cucu perempuan',c('gdau'),1]]});else if(!c('dau'))add(lb('Cucu perempuan',c('gdau')),c('gdau')>1?2/3:1/2);else if(c('dau')==1)add(lb('Cucu perempuan',c('gdau')),1/6)}
 if(c('ms')&&!desc&&!asc)add(lb('Saudara seibu',c('ms')),c('ms')==1?1/6:1/3);
 const fsA=!mD&&!asc;
 if(fsA){if(c('fb'))A.push({p:4,m:[['Saudara laki-laki kandung',c('fb'),2],['Saudara perempuan kandung',c('fs'),1]]});else if(c('fs')){if(fD)A.push({p:4,m:[['Saudara perempuan kandung',c('fs'),1]]});else add(lb('Saudara perempuan kandung',c('fs')),c('fs')>1?2/3:1/2)}}
 if(fsA&&!c('fb')&&!(c('fs')&&fD)){if(c('pb'))A.push({p:5,m:[['Saudara laki-laki seayah',c('pb'),2],['Saudara perempuan seayah',c('ps'),1]]});else if(c('ps')){if(!c('fs'))add(lb('Saudara perempuan seayah',c('ps')),c('ps')>1?2/3:1/2);else if(c('fs')==1)add(lb('Saudara perempuan seayah',c('ps')),1/6)}}
 let r=1-F.reduce((q,x)=>q+x.f,0);A.sort((a,b)=>a.p-b.p);
 if(r>1e-9&&A.length){const g=A[0],t=g.m.reduce((q,x)=>q+x[1]*x[2],0);g.m.forEach(([n,k,w])=>{if(!k)return;const f=r*k*w/t,row=F.find(x=>x.n==n);row?row.f+=f:F.push({n:lb(n,k)+' (ashabah)',f})});r=0}
 const tot=F.reduce((q,x)=>q+x.f,0);if(tot>1+1e-9){F.forEach(x=>x.f/=tot);N.push('Terjadi awl: bagian setiap ahli waris dikurangi secara proporsional.')}
 else if(r>1e-9&&F.length){const B=F.filter(x=>!/^(Suami|Istri)/.test(x.n)),T=B.length?B:F,t=T.reduce((q,x)=>q+x.f,0);T.forEach(x=>x.f+=r*x.f/t);N.push('Sisa harta dikembalikan kepada ahli waris (radd).')}
 return {rows:F,notes:N}}
const fr=f=>{for(const d of [1,2,3,4,5,6,8,9,10,12,15,16,18,20,24,36,48,72])if(Math.abs(f*d-Math.round(f*d))<1e-6)return Math.round(f*d)+'/'+d;return ''};
P.waris=()=>({html:head('Kalkulator waris')+`<p class="mut">Simulasi pembagian harta pusaka (faraidh). Masukkan harta bersih setelah biaya jenazah, wasiat, dan utang.</p><div class="res stick" id="rs"></div><label>Total harta bersih (Rp)</label><input class="in" id="h" inputmode="numeric" placeholder="0"><label>Pasangan</label>${seg('sp',[['','Tidak ada'],['suami','Suami'],['istri','Istri']],'')}<div id="nir" hidden style="margin-top:8px"><div class="srw" style="padding:8px 0"><span class="t">Jumlah istri</span>${stp('ni',1,4)}</div></div><h2>Ahli waris yang masih hidup</h2><div class="list">${WH.map(w=>`<div class="srw"><span class="t">${w[1]}</span>${stp(w[0],0,w[2])}</div>`).join('')}</div>`,
 init(){const V={sp:'',ni:1};const go=()=>{const h=+$('#h').value.replace(/\D/g,'')||0,R=faraidh(V);$('#rs').innerHTML=R.rows.length?R.rows.map(x=>`<div class="sw" style="padding:8px 0"><span>${x.n}<br><small class="mut">${fr(x.f)?fr(x.f)+' · ':''}${(x.f*100).toFixed(2)}%</small></span><b>${rp(h*x.f)}</b></div>`).join('')+R.notes.map(n=>`<p class="mut" style="margin:8px 0 0">${n}</p>`).join('')+'<p class="mut" style="margin:8px 0 0">Simulasi ini ringkas. Untuk kasus nyata, konsultasikan ke ahli faraidh atau pengadilan agama.</p>':'Tambahkan minimal satu ahli waris.'};
  $('#h').oninput=go;segBind('sp',v=>{V.sp=v;$('#nir').hidden=v!='istri';go()});$$('.stp').forEach(e=>e.onclick=x=>{const b=x.target.closest('button');if(!b)return;const k=e.dataset.k,mx=+e.dataset.max,mn=k=='ni'?1:0;V[k]=Math.max(mn,Math.min(mx,(V[k]||0)+ +b.dataset.s));$('b',e).textContent=V[k];go()});go()}});
/* ---------- Kalender: hari besar, puasa sunnah, rincian per tanggal ---------- */
const HJ={'1/1':'Tahun Baru Hijriah','1/10':'Hari Asyura','3/12':'Maulid Nabi Muhammad SAW','7/27':"Isra Mi'raj",'9/1':'Awal Ramadan','9/17':"Nuzulul Qur'an",'10/1':'Idulfitri','12/9':'Hari Arafah','12/10':'Iduladha'},GM={'1-1':'Tahun Baru Masehi','5-1':'Hari Buruh','6-1':'Hari Lahir Pancasila','8-17':'HUT Kemerdekaan RI','12-25':'Hari Natal'};
const HK=(y,m,d)=>new Intl.DateTimeFormat('en-u-ca-islamic-umalqura',{month:'numeric',day:'numeric'}).format(new Date(y,m,d)).split('/').map(Number);
function info(y,m,d){const [hm,hd]=HK(y,m,d),w=new Date(y,m,d).getDay(),ev=[],pu=[];let haram=false;const e=HJ[hm+'/'+hd],g=GM[(m+1)+'-'+d];if(e)ev.push(e);if(g)ev.push(g);
 if(hm==9)pu.push('Puasa Ramadan (wajib)');else if((hm==10&&hd==1)||(hm==12&&hd>=10&&hd<=13)){haram=true;pu.push('Diharamkan berpuasa')}
 else{if(hm==1&&hd==9)pu.push("Puasa Tasu'a");if(hm==1&&hd==10)pu.push('Puasa Asyura');if(hm==12&&hd==9)pu.push('Puasa Arafah');if(hm==12&&hd<=8)pu.push('Puasa awal Zulhijah');if(hm==10&&hd>=2&&hd<=7)pu.push('Puasa 6 hari Syawal');if(hd>=13&&hd<=15)pu.push('Puasa Ayyamul Bidh');if(w==1)pu.push('Puasa sunnah Senin');if(w==4)pu.push('Puasa sunnah Kamis')}
 return {hd,hm,ev,pu,haram}}
let CAL=null;
P.kalender=()=>{const t=new Date();CAL=CAL||{y:t.getFullYear(),m:t.getMonth(),d:t.getDate()};const {y,m}=CAL,f=new Date(y,m,1).getDay(),n=new Date(y,m+1,0).getDate(),now=y==t.getFullYear()&&m==t.getMonth();CAL.d=Math.min(CAL.d,n);
 const a=hf(new Date(y,m,1),{month:'long'}),b=hf(new Date(y,m,n),{month:'long',year:'numeric'});
 const sel=d=>{const k=info(y,m,d),dt=new Date(y,m,d);return `<b>${HARI[dt.getDay()]} ${pas(y,m,d)}, ${dt.toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'})}</b><br><span class="mut">${hf(dt,{day:'numeric',month:'long',year:'numeric'})}</span><div>${k.ev.map(e=>`<span class="tag t1">${e}</span>`).join('')}${k.pu.map(e=>`<span class="tag ${k.haram?'t3':'t2'}">${e}</span>`).join('')}${k.ev.length+k.pu.length?'':'<span class="mut" style="display:block;margin-top:6px">Tidak ada peringatan khusus.</span>'}</div>`};
 const cells=Array.from({length:n},(_,i)=>{const d=i+1,k=info(y,m,d),w=(f+i)%7;return `<button type="button" class="cd ${now&&d==t.getDate()?'t':''} ${d==CAL.d?'s':''} ${w==0?'sun':w==5?'fri':''}" data-d="${d}"><small class="hj">${k.hd}</small>${d}<small>${pas(y,m,d)}</small><span class="dots">${k.ev.length?'<i class="dg1"></i>':''}${k.pu.length&&!k.haram?'<i class="dg2"></i>':''}${k.haram?'<i class="dg3"></i>':''}</span></button>`}).join('');
 const L=[];for(let d=1;d<=n;d++){const k=info(y,m,d);k.ev.forEach(e=>L.push([d,e,'t1']));k.pu.filter(p=>!/Senin|Kamis/.test(p)).forEach(p=>L.push([d,p,k.haram?'t3':'t2']))}
 return {html:`<div class="mn"><button data-n="-1" aria-label="Bulan sebelumnya">${ic('back',24)}</button><div><b>${new Date(y,m,1).toLocaleDateString('id-ID',{month:'long',year:'numeric'})}</b><br><small class="mut">${a==b.split(' ')[0]?b:a+' - '+b}</small></div><button data-n="1" aria-label="Bulan berikutnya">${ic('next',24)}</button></div>
 <div class="cal">${HARI.map(d=>`<div class="h">${d.slice(0,3)}</div>`).join('')}${'<span></span>'.repeat(f)}${cells}</div>
 <div class="card" id="cdet" style="margin-top:12px">${sel(CAL.d)}</div>
 <div class="leg"><span><i class="dg1"></i>Hari besar</span><span><i class="dg2"></i>Puasa</span><span><i class="dg3"></i>Haram puasa</span><button class="btn s" id="td">Hari ini</button></div>
 <h2>Hari besar dan puasa bulan ini</h2>${L.length?list(L,x=>`<div class="row"><span class="num">${x[0]}</span><span class="t">${x[1]}</span><span class="tag ${x[2]}" style="margin:0">${x[2]=='t1'?'Hari besar':x[2]=='t3'?'Haram puasa':'Puasa'}</span></div>`):'<div class="card mut">Tidak ada peringatan bulan ini.</div>'}<p class="mut">Angka kecil kiri atas adalah tanggal Hijriah (Umm al-Qura). Awal bulan resmi di Indonesia bisa berbeda satu hari. Puasa Senin dan Kamis tidak dicantumkan di daftar.</p>`,
 init(){$$('[data-n]').forEach(x=>x.onclick=()=>{const d=new Date(CAL.y,CAL.m+ +x.dataset.n,1);CAL={y:d.getFullYear(),m:d.getMonth(),d:1};route()});$$('.cd').forEach(x=>x.onclick=()=>{CAL.d=+x.dataset.d;$$('.cd').forEach(z=>z.classList.toggle('s',z==x));$('#cdet').innerHTML=sel(CAL.d)});$('#td').onclick=()=>{CAL=null;route()}}}};


/* ---------- Zona waktu, kota, pemilih lokasi ---------- */
const tzl=()=>({7:'WIB',8:'WITA',9:'WIT'}[S.loc.tz??-new Date().getTimezoneOffset()/60]||'');
const locNow=()=>{const n=new Date(),tz=S.loc.tz??-n.getTimezoneOffset()/60,u=n.getUTCHours()+n.getUTCMinutes()/60+n.getUTCSeconds()/3600+tz;return((u%24)+24)%24};
const CITIES=[['Banda Aceh',5.5483,95.3238,7],['Medan',3.5952,98.6722,7],['Padang',-0.9471,100.4172,7],['Pekanbaru',0.5071,101.4478,7],['Batam',1.0456,104.0305,7],['Jambi',-1.6101,103.6131,7],['Palembang',-2.9761,104.7754,7],['Bengkulu',-3.8004,102.2655,7],['Bandar Lampung',-5.4294,105.261,7],['Jakarta',-6.2088,106.8456,7],['Tangerang',-6.1783,106.6319,7],['Serang',-6.1201,106.1503,7],['Bekasi',-6.2383,106.9756,7],['Depok',-6.4025,106.7942,7],['Bogor',-6.5971,106.806,7],['Sukabumi',-6.9277,106.93,7],['Kadudampit, Sukabumi',-6.88,106.91,7],['Cianjur',-6.82,107.1425,7],['Bandung',-6.9175,107.6191,7],['Garut',-7.2279,107.9087,7],['Tasikmalaya',-7.3274,108.2207,7],['Cirebon',-6.7063,108.557,7],['Semarang',-6.9667,110.4167,7],['Yogyakarta',-7.7956,110.3695,7],['Surakarta (Solo)',-7.5755,110.8243,7],['Surabaya',-7.2575,112.7521,7],['Malang',-7.9666,112.6326,7],['Pontianak',-0.0263,109.3425,7],['Palangka Raya',-2.2161,113.9135,7],['Banjarmasin',-3.3194,114.5908,8],['Balikpapan',-1.2379,116.8529,8],['Samarinda',-0.5022,117.1536,8],['Denpasar',-8.6705,115.2126,8],['Mataram',-8.5833,116.1167,8],['Kupang',-10.1772,123.607,8],['Makassar',-5.1477,119.4327,8],['Palu',-0.8917,119.8707,8],['Manado',1.4748,124.8421,8],['Kendari',-3.9985,122.513,8],['Ambon',-3.6954,128.1814,9],['Jayapura',-2.5337,140.7181,9]];
const locCard=()=>`<div class="card lc"><span class="si">${ic('pin',20)}</span><span class="t"><b>${S.loc.n}</b><br><small class="mut">${S.loc.lat.toFixed(3)}, ${S.loc.lng.toFixed(3)} · ${tzl()}</small></span><button class="btn s" data-loc>Ubah</button></div>`;
function msheet(t,h){const e=document.createElement('div');e.className='back-d';e.innerHTML=`<div class="sheet" role="dialog"><b>${t}</b><div style="margin:8px 0">${h}</div><button class="btn" style="width:100%" data-x>Mengerti</button></div>`;document.body.append(e);e.onclick=x=>{if(x.target==e||x.target.closest('[data-x]'))e.remove()}}
function lsheet(){const e=document.createElement('div');e.className='back-d';let tz=S.loc.tz??7;e.innerHTML=`<div class="sheet" style="max-height:88vh;overflow:auto" role="dialog"><b>Atur lokasi</b><button class="btn" id="lg" style="width:100%;margin:10px 0">${ic('pin',16)} Gunakan lokasi saya (GPS)</button><input class="in" id="lq" type="search" placeholder="Cari kota…"><div id="ll" class="list" style="max-height:200px;overflow:auto;margin-bottom:10px"></div><h2>Atau isi manual</h2><input class="in" id="ln" placeholder="Nama lokasi"><div style="display:flex;gap:8px"><input class="in" id="la" inputmode="decimal" placeholder="Lintang (-6.9175)"><input class="in" id="lo" inputmode="decimal" placeholder="Bujur (107.6191)"></div>${seg('lz',[[7,'WIB'],[8,'WITA'],[9,'WIT']],tz)}<button class="btn" id="ls" style="width:100%;margin-top:12px">Simpan lokasi</button></div>`;document.body.append(e);
 const set=l=>{S.loc=l;save();e.remove();toast('Lokasi: '+l.n);route()},draw=()=>{const q=$('#lq',e).value.toLowerCase(),L=CITIES.map((c,i)=>[c,i]).filter(x=>x[0][0].toLowerCase().includes(q));$('#ll',e).innerHTML=L.length?L.map(x=>`<div class="row" data-c="${x[1]}"><span class="t">${x[0][0]}</span><small class="mut">${{7:'WIB',8:'WITA',9:'WIT'}[x[0][3]]}</small></div>`).join(''):'<div class="row mut">Kota tidak ditemukan. Isi manual di bawah.</div>'};
 draw();$('#lq',e).oninput=draw;segBind('lz',v=>tz=+v);$('#lg',e).onclick=()=>gps(()=>{e.remove();route()});
 $('#ls',e).onclick=()=>{const la=parseFloat($('#la',e).value.replace(',','.')),lo=parseFloat($('#lo',e).value.replace(',','.'));if(!(la>=-90&&la<=90&&lo>=-180&&lo<=180))return toast('Lintang dan bujur belum valid');set({n:$('#ln',e).value.trim()||'Lokasi manual',lat:la,lng:lo,tz})};
 e.onclick=x=>{const r=x.target.closest('[data-c]');if(r){const c=CITIES[+r.dataset.c];return set({n:c[0],lat:c[1],lng:c[2],tz:c[3]})}if(x.target==e)e.remove()}}
const zoomBar=()=>`<div class="zb"><span class="mut">Ukuran teks</span><button type="button" data-z="-2" aria-label="Perkecil">A−</button><b>${S.fs}</b><button type="button" data-z="2" aria-label="Perbesar">A+</button></div>`;
const NOTE=`<div class="note">${ic('info',18)}<span>Aplikasi masih dalam masa pengembangan. Bila ada yang keliru, mohon konfirmasi lewat <a href="#/tentang">Laporkan bug</a>.</span><button class="ib2" data-nb aria-label="Tutup">×</button></div>`;
/* ---------- Jadwal salat ---------- */
P.jadwal=()=>({html:head('Jadwal salat')+`<div class="hero jh"><small id="jn"></small><div class="big" id="jc">--</div><small id="jl"></small></div><div style="margin-top:12px">${locCard()}</div><div id="jt" style="margin-top:12px"></div><p class="mut">${hijri()}. Waktu dihitung di perangkat (Subuh 20°, Isya 18°), sehingga tetap bekerja tanpa internet. Selisih 1–3 menit dari jadwal resmi wajar; tambahkan ihtiyat bila perlu.</p>`,
 init(){const tick=()=>{if(!$('#jt'))return clearInterval(P.tj);const T=waktu(new Date(),S.loc),c=locNow(),idx=T.findIndex((x,i)=>i!=1&&x[1]>c),k=idx<0?0:idx;let df=T[k][1]-c;if(idx<0)df+=24;const D=Math.max(0,Math.round(df*60)),h=D/60|0,m=D%60;
  $('#jn').textContent='Menuju waktu '+T[k][0];$('#jc').textContent=(h?h+' jam ':'')+m+' menit';$('#jl').textContent=T[k][0]+' pukul '+hm(T[k][1])+' '+tzl()+' · '+S.loc.n;
  $('#jt').innerHTML=list(T,(x,i)=>`<div class="row ${i==k?'nx':''}"><span class="t">${x[0]}</span><b>${hm(x[1])}</b></div>`)};tick();clearInterval(P.tj);P.tj=setInterval(tick,15000)}});
/* ---------- Wirid, doa, Asmaul Husna ---------- */
const items=(t,i)=>{const D=(t=='w'?WD:DD)[i]||[],U=t=='w'?SUB[i]:null;return U?U.map(n=>({n,j:D.findIndex(x=>x[0].toLowerCase().includes(n.toLowerCase()))})):D.map((x,j)=>({n:x[0],j}))};
const catList=(t,N)=>list(N,(n,i)=>{const L=items(t,i),as=t=='w'&&i==2,href=as?'#/asma':L.length?`#/baca/${t}/${i}`:`#/segera/${encodeURIComponent(n)}`;return `<a class="row" href="${href}"><span class="num">${i+1}</span><span class="t">${n}<br><small>${as?'99 nama':L.length?L.length+' bacaan':'Segera hadir'}</small></span>${ic('next',18)}</a>`});
P.baca=(t,i)=>{const N=t=='w'?WN:MENU.doa;if(!N[i])return P.wirid();const L=items(t,i);return {html:head(N[i],'#/wirid')+(L.length?list(L,(x,k)=>`<a class="row" href="${x.j>=0?`#/bacaan/${t}/${i}/${x.j}`:`#/segera/${encodeURIComponent(x.n)}`}"><span class="num">${k+1}</span><span class="t">${x.n}<br><small>${x.j>=0?'Ketuk untuk membaca':'Segera hadir'}</small></span>${ic('next',18)}</a>`):'<div class="card mut">Segera hadir.</div>')}};
P.bacaan=(t,i,j)=>{const x=(t=='w'?WD:DD)[i]?.[j];if(!x)return P.wirid();return {html:head(x[0],`#/baca/${t}/${i}`,RS)+zoomBar()+`<div class="card">${x[1]?`<div class="ar2">${x[1]}</div>`:''}<div id="ref"></div>${x[2]?`<p style="margin:8px 0 0">${x[2]}</p>`:''}${x[3]=='#/tasbih'?`<a class="btn s" style="display:inline-block;margin-top:10px" href="#/tasbih">Buka penghitung tasbih</a>`:''}</div><p class="mut">Mohon periksakan teks ini kepada ustaz atau kiai sebelum dijadikan rujukan.</p>`,
 init(){const m=(x[3]||'').match(/quran\/(\d+)\/(\d+)/);if(m)AY(+m[1],+m[2],+m[2]).then(h=>{$('#ref').innerHTML=h}).catch(()=>{$('#ref').innerHTML='<p class="mut">Teks Al-Qur\'an belum tersimpan. Sambungkan internet sekali untuk mengunduhnya.</p>'})}}};
/* ---------- Pembaca: mushaf (layar penuh) & pemutar ---------- */
const drawAy=(el,A,n)=>{if(S.full){let b='';const W=A.map(x=>x.a);if(n!=1&&W[0].startsWith('بِسْمِ')){W[0]=W[0].split(' ').slice(4).join(' ');b='<div class="bsm">بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ</div>'}el.innerHTML=`<div class="mushaf" style="font-size:${S.fs}px">${b}${W.map((t,i)=>`<span class="ayt" id="a${i+1}">${t}<span class="mk">${(i+1).toLocaleString('ar-EG')}</span></span>`).join(' ')}</div>`}
 else el.innerHTML=A.map((x,i)=>`<div class="ay" id="a${i+1}"><div class="ah"><span class="n">${i+1}</span><button class="bm ${(S.bm||[]).includes(n+':'+(i+1))?'on':''}" data-bm="${n}:${i+1}" aria-label="Penanda ayat">${ic('star',18)}</button></div><div class="ar" style="font-size:${S.fs}px">${x.a}</div><p class="lt" ${S.lt?'':'hidden'}>${x.l}</p><p class="mut tr" style="margin:6px 0 0" ${S.tr?'':'hidden'}>${x.t}</p></div>`).join('')};
const qplayer=()=>{const au=$('#au');if(!au)return;$('#pp').onclick=()=>au.paused?au.play().catch(()=>toast('Audio butuh internet')):au.pause();au.onplay=()=>$('#pp').innerHTML=ic('pause',20);au.onpause=()=>$('#pp').innerHTML=ic('play',20);au.ontimeupdate=()=>{$('#pg').style.width=(au.currentTime/au.duration*100||0)+'%'}};
/* ---------- Pembayaran, zoom, pemberitahuan, lokasi (satu pendengar klik) ---------- */
document.addEventListener('click',e=>{const t=e.target;
 if(t.closest('[data-loc]'))return lsheet();
 const z=t.closest('[data-z]');if(z){S.fs=Math.max(22,Math.min(56,S.fs+ +z.dataset.z));save();$$('#view .ay .ar,#view .ay2 .ar,#view .ar2,#view .mushaf').forEach(x=>x.style.fontSize=S.fs+'px');$$('.zb b').forEach(b=>b.textContent=S.fs);return}
 if(t.closest('[data-nb]')){S.nb=1;save();t.closest('.note').remove();return}
 const l=t.closest('[data-lanjut]');if(l){const c=l.closest('[data-pay]'),r=c.querySelector('input[name=pm]:checked'),b=BANK[r?+r.value:0],nom=(c.querySelector('[data-nom]').value||'').replace(/\D/g,'');(navigator.clipboard?navigator.clipboard.writeText(b[1]):Promise.reject()).catch(()=>{});msheet('Pembayaran langsung segera hadir',`<p>Fitur lanjut pembayaran langsung ke aplikasi ${b[0]} masih dalam tahap pengembangan.</p><p>Nomor tujuan <b>${b[1]}</b> (${b[0]}) ${nom?'dengan nominal <b>'+rp(nom)+'</b> ':''}sudah disalin. Silakan buka aplikasi ${b[0]} atau bank pilihanmu, lalu tempel nomor tersebut.</p>`)}});
/* ---------- Tentang & laporan ---------- */
P.tentang=()=>({html:head('Tentang')+`<div class="note">${ic('info',18)}<span>Aplikasi ini masih dalam masa pengembangan. Jika ada yang keliru atau salah tulis, mohon konfirmasikan lewat laporan.</span></div>
<div class="card" style="margin-top:12px"><b>Fadzkuruuni</b><p class="mut" style="margin:4px 0 0">Aplikasi ibadah harian: Al-Qur'an, wirid dan doa, jadwal salat, kiblat, zakat, waris, dan kalender Hijriah dalam satu aplikasi yang bisa dipakai offline.</p></div>
<h2>Bantu kami</h2><div class="list sg">${lk('#/lapor','flag','Laporkan bug atau kesalahan penulisan')}</div>
<h2>Pondok pesantren</h2><div class="card"><b>Ponpes Tahfidz Qur'an Fadzkuruuni (Majelis Fadzkuruuni)</b><p style="margin:6px 0 4px"><b>Pendiri: Ustadz Mahbubillah</b></p><p class="mut" style="margin:4px 0">Jl. Cipetir Girang, Kp. Cibuntu Kaler, Sukamaju, Kec. Kadudampit, Kab. Sukabumi, Jawa Barat 43153</p><small class="mut">Alamat dari sumber publik; belum diverifikasi ke pihak pesantren.</small></div>
<h2>Pengembang</h2><div class="card">Muhammad Hilmi Azkia Rahman</div>
<h2>Sumber dan lisensi</h2><div class="card"><p style="margin:0 0 8px">Lisensi kode aplikasi belum ditetapkan oleh pemilik proyek.</p><p style="margin:0 0 8px">Konten keagamaan dari pihak ketiga hanya dimuat jika izin penggunaannya sudah terverifikasi, lengkap dengan nama sumbernya.</p><p style="margin:0">Doa, wirid, dan hadits yang tampil saat ini adalah teks ringkas yang umum dikenal. Mohon diperiksakan kepada ustaz atau kiai.</p></div><p class="mut" style="text-align:center">Versi ${VER} · © 2026 Fadzkuruuni</p>`});

/* ---------- Pembantu dari versi 1.5 ---------- */
const VER='1.5.0';
const REPORT={wa:'6289506138191',url:'',nocors:false};
const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const mk=(c,h)=>{const e=document.createElement('div');e.className=c;e.innerHTML=h;document.body.append(e);return e};
function dlg(t,m,fn){const e=mk('dlg',`<div role="dialog"><div class="ok">${ic('check',30)}</div><b style="font-size:18px">${t}</b><p class="mut" style="margin:8px 0 16px">${m}</p><button class="btn" style="width:100%">Tutup</button></div>`);e.onclick=x=>{if(x.target==e||x.target.tagName=='BUTTON'){e.remove();fn&&fn()}}}
let LAST='#/';S.tt=S.tt||33;
const RS=`<button class="ib" data-rs aria-label="Pengaturan baca">${ic('sliders',20)}</button>`;
/* ---------- Tasbih: halaman + tombol melayang ---------- */
const tUpd=()=>{const f=$('#fc');if(f)f.textContent=S.tas;const c=$('#c');if(c){c.textContent=S.tas;$('#tg').textContent=S.tas+' / '+S.tt}};
const tap=()=>{S.tas++;if(S.tas>=S.tt){navigator.vibrate?.(80);toast('Target '+S.tt+' tercapai');S.tas=0}else navigator.vibrate?.(12);save();tUpd()};
const ftb=mk('','<button id="fc" aria-label="Tasbih: tambah hitungan">0</button><button id="fr" aria-label="Reset tasbih">↺</button>');ftb.id='ftb';
$('#fc').onclick=tap;$('#fr').onclick=()=>{S.tas=0;save();tUpd()};
const ftUpd=()=>{ftb.hidden=S.ft===false||location.hash.slice(2).split('/')[0]=='tasbih';tUpd()};
P.tasbih=()=>({html:head('Tasbih')+`<button class="cnt" id="c">0</button><div class="mut" style="text-align:center" id="tg"></div><div class="mut" style="text-align:center;margin:16px 0 6px">Target hitungan</div>${seg('tt',[[33,'33'],[99,'99'],[100,'100'],[1000,'1000']],S.tt)}<div style="text-align:center;margin-top:14px"><button class="btn s" id="rz">Reset</button></div>`,
 init(){tUpd();$('#c').onclick=tap;$('#rz').onclick=()=>{S.tas=0;save();tUpd()};segBind('tt',v=>{S.tt=+v;S.tas=0;save();tUpd()})}});


const pn=(P_,N_)=>`<div style="display:flex;gap:8px;margin-top:16px">${P_?`<a class="btn s" href="${P_}">‹ Sebelumnya</a>`:''}${N_?`<a class="btn" href="${N_}">Berikutnya ›</a>`:''}</div>`;
/* ---------- Asmaul Husna: tampil langsung, rincian per nama ---------- */
const refs=s=>s.split(',').filter(Boolean).map(r=>{const [a,b]=r.split(':');return `<a class="chip2" href="#/quran/${a}/${b}">QS. ${NAMA[a-1]}: ${b}</a>`}).join('');
P.asma=n=>{n=+n;if(n&&ASMA[n-1]){const a=ASMA[n-1],X=(ASMX[n-1]||'').split('|'),sec=(h,b)=>b?`<h3 class="sec">${h}</h3><div class="card">${b}</div>`:'';
  return {html:head(n+'. '+a[1],'#/asma',RS)+`<div class="card" style="text-align:center"><div class="ar2" style="text-align:center">${a[3]}</div><b>${a[1]}</b><br><span class="mut">${a[2]}</span></div>`+sec('Makna',X[1])+(X[0]||X[4]?`<h3 class="sec">Dalil</h3><div class="card">${X[0]?`<div class="chips" style="margin:0 0 8px;flex-wrap:wrap;overflow:visible">${refs(X[0])}</div>`:''}${X[4]?`<p style="margin:0">${X[4]}</p>`:''}</div>`:'')+sec('Penerapan dalam hidup',X[2])+sec('Kisah',X[3])+pn(n>1?'#/asma/'+(n-1):'',n<99?'#/asma/'+(n+1):'')+'<p class="mut" style="margin-top:12px">Sebagian nama tidak disebut persis sebagai nama dalam Al-Qur\'an; rujukan ayat bersifat penunjuk makna, dan sebagian bersumber dari riwayat At-Tirmidzi. Mohon periksakan kepada ustaz atau kiai.</p>'}}
 return {html:head('Asmaul Husna','#/wirid',RS)+'<p class="mut" style="margin:0 0 8px">Ketuk sebuah nama untuk melihat makna, dalil, penerapan, dan kisahnya.</p>'+list(ASMA,a=>`<a class="row" href="#/asma/${a[0]}"><span class="num">${a[0]}</span><span class="t">${a[1]}<br><small>${a[2]}</small></span><span class="ar">${a[3]}</span></a>`)}};


const shrink=f=>new Promise(r=>{const i=new Image,u=URL.createObjectURL(f);i.onload=()=>{const s=Math.min(1,1280/Math.max(i.width,i.height)),c=document.createElement('canvas');c.width=i.width*s;c.height=i.height*s;c.getContext('2d').drawImage(i,0,0,c.width,c.height);URL.revokeObjectURL(u);c.toBlob(r,'image/jpeg',.72)};i.onerror=()=>r(null);i.src=u});
const b2d=b=>new Promise(o=>{const f=new FileReader;f.onload=()=>o(f.result);f.readAsDataURL(b)});
const rtxt=r=>`*Laporan Fadzkuruuni v${VER}*\nJenis: ${r.jenis}\nNama: ${r.nama||'-'}\nHalaman: ${r.hal||'-'}\n\n${r.pesan}`;
const post=async r=>{const fd=new FormData();['nama','jenis','pesan','hal'].forEach(k=>fd.append(k,r[k]||''));fd.append('versi',VER);if(r.foto)fd.append('foto',r.foto,'foto.jpg');try{const x=await fetch(REPORT.url,{method:'POST',body:fd,mode:REPORT.nocors?'no-cors':'cors',headers:REPORT.nocors?undefined:{Accept:'application/json'}});return x.ok||x.type=='opaque'}catch(e){return false}};
async function flushQ(){if(!REPORT.url||!(S.rq||[]).length||!navigator.onLine)return;const rest=[];for(const q of S.rq){const f=q.foto?await(await fetch(q.foto)).blob():null;if(!await post({...q,foto:f}))rest.push(q)}S.rq=rest;save()}
addEventListener('online',flushQ);flushQ();
async function sendReport(r){const txt=rtxt(r);
 if(REPORT.url){if(await post(r))return 'sent';S.rq=[...(S.rq||[]),{...r,foto:r.foto?await b2d(r.foto):null}];save();return 'queued'}
 if(r.foto&&navigator.canShare){const files=[new File([r.foto],'laporan.jpg',{type:'image/jpeg'})];if(navigator.canShare({files})){try{await navigator.share({files,text:txt,title:'Laporan Fadzkuruuni'});return 'share'}catch(e){return e.name=='AbortError'?'cancel':'wa'}}}
 const w=open(`https://wa.me/${REPORT.wa}?text=${encodeURIComponent(txt)}`,'_blank');if(!w)location.href=`https://wa.me/${REPORT.wa}?text=${encodeURIComponent(txt)}`;return r.foto?'wafoto':'wa'}
P.lapor=()=>({html:head('Laporkan masalah','#/tentang')+`<p class="mut" style="margin:0 0 10px">Menemukan bug atau kesalahan penulisan (Arab, arti, ejaan)? Laporan akan dikirim ke WhatsApp pengembang.</p><label>Nama (opsional)</label><input class="in" id="rn" maxlength="60" placeholder="Nama kamu"><label>Jenis laporan</label>${seg('rj',[['Bug','Bug'],['Salah tulis','Salah tulis'],['Saran','Saran']],'Bug')}<label style="margin-top:12px">Pesan</label><textarea class="in" id="rm" rows="5" maxlength="1500" placeholder="Di halaman mana, apa yang salah, dan seharusnya bagaimana"></textarea><label>Foto atau tangkapan layar (opsional)</label><label class="ph" for="rf">${ic('camera',20)} <span id="rfn">Pilih foto</span></label><input type="file" id="rf" accept="image/*" hidden><img id="rp" alt="Pratinjau foto" hidden><button class="btn" id="rk" style="width:100%;margin-top:12px">Kirim laporan</button>`,
 init(){let J='Bug',F=null;segBind('rj',v=>J=v);
  $('#rf').onchange=async e=>{const f=e.target.files[0];if(!f)return;F=await shrink(f);if(!F){toast('Foto tidak bisa dibaca');return}$('#rfn').textContent=f.name;const p=$('#rp');p.src=URL.createObjectURL(F);p.hidden=false};
  $('#rk').onclick=async()=>{const pesan=$('#rm').value.trim();if(pesan.length<5)return toast('Tulis pesan laporan terlebih dahulu');const b=$('#rk');b.disabled=true;b.textContent='Mengirim…';
   const st=await sendReport({nama:$('#rn').value.trim(),jenis:J,pesan,hal:LAST,foto:F});b.disabled=false;b.textContent='Kirim laporan';if(st=='cancel')return;
   const m={sent:'Laporanmu sudah terkirim. Masukanmu membantu kami memperbaiki Fadzkuruuni.',queued:'Laporanmu tersimpan dan akan dikirim otomatis saat internet tersedia.',share:'Terima kasih. Pastikan laporan terkirim ke WhatsApp pengembang di aplikasi yang terbuka.',wa:'WhatsApp terbuka dengan isi laporanmu. Tekan tombol kirim di sana untuk menyelesaikannya.',wafoto:'WhatsApp terbuka dengan isi laporanmu. Lampirkan fotonya secara manual di chat, lalu tekan kirim.'}[st];
   dlg('Terima kasih atas laporanmu',m,()=>location.hash='#/tentang')}}});


/* ---------- Maulid ---------- */
const ADL=['Pembuka (Inna fatahna…)','Bagian I: Alhamdulillahil ladzi…','Bagian II: Nabba\'anallahu…','Bagian III: Hadza wa qad nasyara…','Bagian IV: Lamma dana waqtu…','Bagian V: Wulidal Habib…','Bagian VI: Hadza wa qad nasya\'a','Bagian VII: Wa atahu jibrilu…','Mahallul Qiyam','Doa (Ad-du\'a)'];
P.maulid=i=>{if(i==5)return {html:head("Maulid Adl-Dliya'ul Lami'",'#/maulid')+'<p class="mut">Daftar bagian. Isi bacaan belum dimuat karena teks bersih dan izin penggunaannya masih disiapkan.</p>'+soon(ADL)};return {html:head('Maulid')+list(MENU.maulid,(m,k)=>`<a class="row" href="${k==5?'#/maulid/5':'#/segera/'+encodeURIComponent(m)}"><span class="num">${k+1}</span><span class="t">${m}<br><small>${k==5?ADL.length+' bagian':'Segera hadir'}</small></span>${ic('next',18)}</a>`)}};
/* ---------- Hadits, kata mutiara, sapaan, kata-kata bergulir ---------- */
P.hadits=()=>({html:head('Hadits Nabi')+'<p class="mut">Hadits masyhur secara ringkas. Periksa kembali ke kitab asli untuk rujukan.</p>'+HADITS.map(h=>`<div class="card" style="margin-bottom:10px"><div class="ar2">${h[0]}</div><p style="margin:6px 0">${h[1]}</p><small class="mut">${h[2]}</small><div style="margin-top:8px"><button class="btn s" data-copy="${esc(h[0]+'\n'+h[1]+'\n('+h[2]+')')}">Salin</button></div></div>`).join('')});
P.mutiara=()=>({html:head('Kata Mutiara')+QUOTES.map(q=>q[1]).concat(S.qs||[]).map(t=>`<div class="card" style="margin-bottom:10px"><p style="margin:0 0 8px">“${esc(t)}”</p><button class="btn s" data-copy="${esc(t)}">Salin</button></div>`).join('')});
const periode=()=>{const h=locNow();return h<4?'malam':h<10?'pagi':h<15?'siang':h<18?'sore':'malam'};
const GREET=()=>`<div class="gr"><small class="mut">${new Date().toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'})} · ${hijri()}</small><div class="gh">Selamat ${periode()}${S.nm?', '+esc(S.nm):''}</div></div>`;
function qrot(){const el=$('#qtx');if(!el)return;let i=Math.floor(Math.random()*97);const show=()=>{const e=$('#qtx');if(!e)return clearInterval(P.tq);const p=periode(),L=[...QUOTES.filter(q=>q[0]==p||q[0]=='any').map(q=>q[1]),...(S.qs||[])];e.classList.remove('in');void e.offsetWidth;e.textContent=L[i++%L.length]||'';e.classList.add('in')};show();clearInterval(P.tq);P.tq=setInterval(show,9000)}
/* ---------- Izin, offline, profil ---------- */
const bdg=n=>`<span class="bdg" data-perm="${n}">…</span>`;
const IZIN=()=>`<h2>Izin</h2><div class="list sg">${row('pin','Lokasi salat',bdg('geolocation'),'<button class="btn s" data-loc>Atur lokasi</button>')}${row('bell','Notifikasi',bdg('notifications'),'<button class="btn s" data-notif>Izinkan</button>')}</div>`;
async function permFill(){for(const el of $$('[data-perm]')){const n=el.dataset.perm;let s='Belum diminta';try{const r=await navigator.permissions.query({name:n});s={granted:'Diizinkan',denied:'Ditolak',prompt:'Belum diminta'}[r.state]||s}catch(e){if(n=='notifications'&&'Notification'in window)s={granted:'Diizinkan',denied:'Ditolak',default:'Belum diminta'}[Notification.permission]||s}el.textContent=s;el.className='bdg '+(s=='Diizinkan'?'':s=='Ditolak'?'no':'mid')}}
const OFFL=()=>`<h2>Mode offline</h2><div class="card"><p class="mut" style="margin:0 0 6px">Aplikasi bisa dibuka tanpa internet setelah dimuat sekali. Unduh teks Al-Qur'an agar tetap bisa dibaca tanpa sinyal.</p>${row('book',"Al-Qur'an (114 surah)",'<span id="oq">Menghitung…</span>','<button class="btn s" id="od">Unduh</button>')}${row('clock','Jadwal salat','Dihitung langsung di perangkat, selalu tersedia offline','')}</div>`;
async function offFill(){try{const k=await (await caches.open('fz-data')).keys(),n=k.filter(r=>/surah\//.test(r.url)).length;$('#oq').textContent=n+' dari 114 surah tersimpan'}catch(e){$('#oq').textContent='Belum ada data tersimpan'}$('#od').onclick=async()=>{const b=$('#od');b.disabled=true;let ok=0;for(let i=1;i<=114;i++){try{await qGet(i);ok++}catch(e){}$('#oq').textContent='Mengunduh '+ok+'/114…'}b.disabled=false;toast(ok==114?"Al-Qur'an siap dibaca offline":'Sebagian gagal; cek internet lalu coba lagi');offFill()}}
const PROFIL=()=>`<h2>Profil</h2><div class="list sg"><div class="srw"><span class="si">${ic('user',20)}</span><span class="t">Nama panggilan<br><small class="mut">Dipakai pada sapaan di Beranda</small></span><input class="in sl2" id="nm" maxlength="24" style="width:150px" value="${esc(S.nm||'')}" placeholder="Nama"></div></div><h2>Kata-kata di Beranda</h2><div class="card"><p class="mut" style="margin:0 0 8px">Kata-kata bergulir di bawah jam dan berganti sesuai waktu (pagi, siang, sore, malam). Tambahkan kata-katamu sendiri.</p><div style="display:flex;gap:8px"><input class="in" id="qn" maxlength="140" placeholder="Tulis kata-kata…" style="margin:0"><button class="btn" data-addq>Tambah</button></div>${(S.qs||[]).map((q,i)=>`<div class="sw"><span>${esc(q)}</span><button class="btn s" data-delq="${i}">Hapus</button></div>`).join('')}</div>`;
/* ---------- Akun Google & sinkron cloud (butuh konfigurasi Firebase; lihat PANDUAN-FIREBASE.md) ---------- */
const FBCFG={apiKey:'',authDomain:'',projectId:'',appId:''};
const cloudOn=()=>!!(FBCFG.apiKey&&FBCFG.projectId);
let FBU=null,FBD=null,cpt=0;const SYNC=['bm','hist','nm','qs','theme','fs','tr','lt','tas','tt','rnd','az','loc','pay','ft','full'];
const ldjs=src=>new Promise((o,r)=>{const e=document.createElement('script');e.src=src;e.onload=o;e.onerror=r;document.head.append(e)});
async function fbInit(){if(!cloudOn()||window.firebase?.apps?.length)return;try{const b='https://www.gstatic.com/firebasejs/10.12.2/';await ldjs(b+'firebase-app-compat.js');await ldjs(b+'firebase-auth-compat.js');await ldjs(b+'firebase-firestore-compat.js');firebase.initializeApp(FBCFG);FBD=firebase.firestore();firebase.auth().onAuthStateChanged(async u=>{FBU=u;if(u)await cloudPull();if($('#cl'))route()})}catch(e){}}
async function cloudPull(){try{const d=await FBD.collection('users').doc(FBU.uid).get();if(d.exists){const r=d.data();if((r.t||0)>(S.ct||0)){SYNC.forEach(k=>{if(r.s&&r.s[k]!==undefined&&r.s[k]!==null)S[k]=r.s[k]});S.ct=r.t;localStorage.fz=JSON.stringify(S);theme()}}else cloudSend()}catch(e){toast('Sinkron gagal. Periksa koneksi.')}}
const cloudSend=async()=>{if(!FBU)return;const s={};SYNC.forEach(k=>s[k]=S[k]??null);const t=Date.now();S.ct=t;localStorage.fz=JSON.stringify(S);try{await FBD.collection('users').doc(FBU.uid).set({s,t})}catch(e){}};
window.cloudPush=()=>{if(!FBU)return;clearTimeout(cpt);cpt=setTimeout(cloudSend,2500)};
const AKUN=()=>`<h2>Akun</h2><div class="list sg" id="cl">${cloudOn()?(FBU?row('user',esc(FBU.displayName||'Akun Google'),esc(FBU.email||'')+' · data tersinkron ke cloud','<button class="btn s" data-gout>Keluar</button>'):row('user','Masuk dengan Google','Simpan penanda, riwayat, dan pengaturan di cloud','<button class="btn" data-gin>Masuk</button>')):row('user','Masuk dengan Google','Belum diaktifkan. Isi konfigurasi Firebase (lihat PANDUAN-FIREBASE.md).','<button class="btn s" disabled>Segera</button>')}</div>`;
cloudOn()&&fbInit();
/* ---------- Pendengar tambahan ---------- */
document.addEventListener('input',e=>{if(e.target.id=='nm'){S.nm=e.target.value;save()}});
document.addEventListener('click',async e=>{const t=e.target;
 if(t.closest('[data-rs]'))return qsheet(()=>route());
 if(t.closest('[data-stop]'))return stopAdzan();
 if(t.closest('[data-tsub]'))return play(0);
 if(t.closest('[data-notif]')){await askNotif();return permFill()}
 if(t.closest('[data-gin]'))return firebase.auth().signInWithPopup(new firebase.auth.GoogleAuthProvider()).catch(()=>toast('Masuk dibatalkan atau gagal'));
 if(t.closest('[data-gout]'))return firebase.auth().signOut().then(()=>{FBU=null;route()});
 if(t.closest('[data-addq]')){const v=($('#qn').value||'').trim();if(!v)return toast('Tulis kata-katanya dulu');S.qs=[...(S.qs||[]),v];save();return route()}
 const d=t.closest('[data-delq]');if(d){S.qs.splice(+d.dataset.delq,1);save();route()}});

/* ---------- Router ---------- */
function route(){if(!location.hash.startsWith('#/lapor'))LAST=location.hash||'#/';$('#au')?.pause();const [a='',b,c,d]=location.hash.slice(2).split('/');const pg=a=='quran'&&b?surah(b,c):(P[a]||P[''])(b,c,d);document.body.classList.toggle('full',!!S.full&&a=='quran'&&!!b);const v=$('#view');v.innerHTML=pg.html;v.scrollTop=0;v.style.animation='none';v.offsetWidth;v.style.animation='';
 $$('#nav a[data-r]').forEach(l=>l.classList.toggle('on',l.dataset.r==(['quran','artikel','kalender','pengaturan'].includes(a)?a:(['','menu'].includes(a)?'':'x'))));pg.init&&pg.init();$$('#view .ar2').forEach(e=>e.style.fontSize=S.fs+'px');ftUpd();
 $$('[data-soon]').forEach(e=>e.onclick=()=>toast('Konten ini segera hadir'))}
addEventListener('hashchange',route);route();
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
